OPTIONS MPRINT MLOGIC SYMBOLGEN; /* SET DEBUGGING OPTIONS */

%LET PULLDATE = %SYSFUNC(today(), yymmdd10.);
%PUT "&PULLDATE";

%LET _1DAY_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-1);
%LET _1DAY = %SYSFUNC(putn(&_1DAY_NUM,yymmdd10.));
%PUT "&_1DAY";

%LET _1MONTH_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-30);
%LET _1MONTH = %SYSFUNC(putn(&_1MONTH_NUM,yymmdd10.));
%PUT "&_1MONTH";

%LET _30MONTH_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-913);
%LET _30MONTH = %SYSFUNC(putn(&_30MONTH_NUM,yymmdd10.));
%PUT "&_30MONTH";

%LET _3YR_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-1095);
%LET _3YR = %SYSFUNC(putn(&_3YR_NUM,yymmdd10.));
%PUT "&_3YR";

%LET _5YR_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-1825);
%LET _5YR = %SYSFUNC(putn(&_5YR_NUM,yymmdd10.));
%PUT "&_5YR";

%LET _15MONTH_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-456);
%LET _15MONTH = %SYSFUNC(putn(&_15MONTH_NUM,yymmdd10.));
%PUT "&_15MONTH";

%LET _18MONTH_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-548);
%LET _18MONTH = %SYSFUNC(putn(&_18MONTH_NUM,yymmdd10.));
%PUT "&_18MONTH";

%LET _24MONTH_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-730);
%LET _24MONTH = %SYSFUNC(putn(&_24MONTH_NUM,yymmdd10.));
%PUT "&_24MONTH";

%LET _36MONTH_NUM = %EVAL(%SYSFUNC(inputn(&pulldate,yymmdd10.))-1095);
%LET _36MONTH = %SYSFUNC(putn(&_36MONTH_NUM,yymmdd10.));
%PUT "&_36MONTH";

%PUT "&_1DAY" "&_1MONTH" "&_30MONTH" "&_3YR" "&_5YR" "&_15MONTH" 
	 "&_18MONTH";

**********************************************************************;
*** IMPORT NEW CROSS SELL FILES. --------------------------------- ***;
*** INSTRUCTIONS HERE: R:\Production\MLA\FILES FOR MLA PROCeSSINg\ ***;
*** XSELL\XSELL TCI DECSION LENDER.txt --------------------------- ***;
*** CHANGE DATES IN THE LINES IMMEDIATELY BELOW ALONG WITH FILE    ***;
*** PATHS. FOR THE FILES PATHS, YOU WILL LIKELY NEED TO CREATE A   ***;
*** NEW FOLDER "CC" IN THE APPROPRIATE MONTH FILE. DO NOT CHANGE   ***;
*** THE ARGUMENT TO THE LEFT OF THE COMMA - ONLY CHANGE WHAT IS TO ***;
*** THE RIGHT OF THE COMMA. ALSO NOTE THE CHANGE TO "ODD" OR "EVEN"***; 
*** BASED ON WHAT IS NEEDED FOR THE CURRENT PULL. ---------------- ***;
**********************************************************************;

*** ASSIGN MACRO VARIABLES --------------------------------------- ***;
DATA 
	_NULL_;

	*** ASSIGN ID MACRO VARIABLES -------------------------------- ***;
	CALL SYMPUT ('RETAIL_ID', 'RetailXS_02.1_2021');
	CALL SYMPUT ('AUTO_ID', 'AUTOXS_02.1_2021');
	CALL SYMPUT ('FB_ID', 'FB_02.1_2021CC');

	*** ASSIGN ODD/EVEN MACRO VARIABLE --------------------------- ***;
	CALL SYMPUT ('ODD_EVEN', 'ODD'); 

	*** ASSIGN DATA FILE MACRO VARIABLE -------------------------- ***;
	
	CALL SYMPUT ('FINALEXPORTFLAGGED', 
		'\\mktg-app01\E\Production\2021\02_February_2021\FBXSCC\FBXS_CC_20210113FLAGGED.txt');
	CALL SYMPUT ('FINALEXPORTDROPPED', 
		'\\mktg-app01\E\Production\2021\02_February_2021\FBXSCC\FBXS_CC_20210113FINAL.txt');
	CALL SYMPUT ('EXPORTMLA', 
		'\\mktg-app01\E\Production\MLA\MLA-INPUT FILES TO WEBSITE\FBCC_20210113.txt');
	CALL SYMPUT ('FINALEXPORTED', 
		'\\mktg-app01\E\Production\2021\02_February_2021\FBXSCC\FBXS_CC_20210113FINAL_HH.cSv');
	CALL SYMPUT ('FINALEXPORTHH', 
		'\\mktg-app01\E\Production\2021\02_February_2021\FBXSCC\FBXS_CC_20210113FINAL_HH.txt');
RUN;

*** NEW TCI DATA - RETAIL AND AUTO ------------------------------- ***;
PROC IMPORT 
	DATAFILE = 
		"\\mktg-app01\E\Production\2021\02_February_2021\FBXSCC\XS_Mail_Pull.xlsx" 
		DBMS = XLSX OUT = XS REPLACE;
	RANGE = "XS Mail PULL$A3:0";
	GETNAMES = YES;
RUN;

*** FORMAT THE `NEWXS` DATASET AND STORE AS `NEWXS2` ------------- ***;
DATA XS2;
	SET XS;

	*** CREATE `SOURCE` VARIABLE AND ASSIGN `LOAN TYPE = AUTO      ***;
	*** INDIRECT` AS `TCICENTRAL` OR `LOAN TYPE = RETAIL` AS       ***; 
	*** `TCIRETAIL` ---------------------------------------------- ***;
	IF 'Loan Type'n = "Auto Indirect" THEN SOURCE = "TCICentral";
	IF 'Loan Type'n = "Retail" THEN SOURCE = "TCIRetail";
	IF SOURCE NE "";

	*** SEPERATE `applicant address` VARIABLE INTO `ADR1`, `CITY`, ***; 
	*** `STATE`, AND `ZIP` VARIABLES WHEN `applicant address` DOES ***; 
	*** NOT CONTAIN THE STRING "Apt" ----------------------------- ***;
	IF FIND('applicant address'n, "Apt") = 0 THEN DO;
		ADR1 = SCAN('applicant address'n, 1, ",");
		CITY = SCAN('applicant address'n, 2, ",");
		STATE = SCAN('applicant address'n, 3, ",");
		ZIP = SCAN('applicant address'n, 4, ",");
	END;

	*** SEPERATE `applicant address` VARIABLE INTO `ADR1`, `ADR2`, ***;
	*** `CITY`, `STATE`, AND `ZIP` VARIABLES WHEN `applicANt       ***;
	*** addreSS` CONTAINS THE STRING "Apt" ----------------------- ***;
	IF FIND('applicant address'n, "Apt") GE 1 THEN DO;
		ADR1 = SCAN('applicant address'n, 1, ",");
		ADR2 = SCAN('applicant address'n, 2, ",");
		CITY = SCAN('applicant address'n, 3, ",");
		STATE = SCAN('applicant address'n, 4, ",");
		ZIP = SCAN('applicant address'n, 5, ",");
	END;

	*** FORMAT `applicANt DOB` AS YYMMDD10 AND STORE IN `DOB`      ***;
	*** VARIABLE. ------------------------------------------------ ***;
	DOB_1 = input('applicant DOB'n, anydtdte32.);
	FORMAT DOB_1 yymmdd10.;
	DOB = PUT(DOB_1, yymmdd10.);
	/*
	DOB = PUT('applicant DOB'n, yymmdd10.);
	*/

	*** FORMAT `application DATE` AS MMDDYY10 -------------------- ***;
	
	'application DATE1'n = PUT('application DATE'n, mmddyy10.);
	

	*** CONCATENATE "TCI" TO `Application NUMBER` AND STORE AS     ***;
	*** `BRACCTNO` VARIABLE -------------------------------------- ***;
	BRACCTNO = CATS("TCI", 'Application Number'n);

	*** SUB-STRING THE LAST 7 DIGITS FROM THE `applicANt SSN`      ***;
	*** VARIABLE AND STORE THEM IN `SSNO1_RT7` VARIABLE ---------- ***;
	SSNO1_RT7 = SUBSTRN('applicant SSN'n, MAX(1, 
		LENGTH('applicant SSN'n) - 6), 7);

	*** DROP THE VARIABLES `Application DATE`, `applicant address`,***;
	*** `applicant address ZIP`, `ApplicANt DOB`, `app. wORk phoNE`***;
	*** FROM NEWXS2 DATASET -------------------------------------- ***;
	DROP 'Application DATE'n 'applicant address'n
		'applicant address zip'n 'applicant DOB'n 'app. wORk phone'n;

	*** RENAME THE `application DATE1`, `applicANt email`,         ***;
	*** `ApplicANt Credit ScORe`, `ApplicANt FIRST NAME`,          ***;
	*** `ApplicANt LAST NAME`, `ApplicANt SSN`, `ApplicANt Middle  ***;
	*** NAME`, `app. cell phoNE`, AND `app. home phoNE` VARIABLES  ***;
	RENAME 
		'application DATE1'n = 'application DATE'n
		'applicant email'n = EMAIL 
		'applicant Credit ScORe'n = CRSCORE
		'applicant FIRST NAME'n = FIRSTNAME
		'ApplicANt LAST NAME'n = LASTNAME 
		'ApplicANt SSN'n = SSNO1
		'ApplicANt Middle NAME'n = MIDDLENAME 
		'app. cell phoNE'n = CELLPHONE 
		'app. home phoNE'n = PHONE;
RUN;

DATA TCI;

	*** SET LENGTH FOR `ADR1`, `CITY`, `STATE`, `ZIP`,             ***;
	*** `MIDDLENAME`, `SOURCE`, AND `BRACCTNO` VARIABLES --------- ***;
	LENGTH 
		ADR1 $40 
		CITY $25 
		STATE $4 
		ZIP $10 
		MIDDLENAME $25 
		SOURCE $11
		BRACCTNO $15;
	SET XS2;
	SSNO1 = STRIP(SSNO1); /* STRIP WHITE SPACE FROM `SSNO1` */
	DOB = COMPRESS(DOB, "-"); /* REMOVE HYPHEN FROM `DOB` */
	FORMAT _CHARACTER_; /* SET CHAR FORMAT TO SAS DEFAULT */
RUN;

*** READ IN DATA FROM `dw.vw_loan_NLS` TABLE. SUBSET FOR RELEVANT  ***;
*** VARIABLES. FILTER TO ISOLATE XS LOANS. STORE AS `XS_L` DATASET ***;
DATA XS_L;
	
	*** SUBSET `dw.vw_loan_NLS` USING RELEVANT VARIABLES --------- ***;
	SET dw.vw_loan_NLS (
		KEEP = OWNST PURCD CIFNO BRACCTNO ID SSNO1 OWNBR SSNO1_RT7 
			SSNO2 LNAMT NETLOANAMOUNT FINCHG LOANTYPE ENTDATE LOANDATE 
			CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE FIRSTPYDATE SRCD 
			POCD POFFDATE PLCD PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER
			CONPROFILE1 DATEPAIDLAST APRATE CRSCORE CURBAL);
	
	*** FILTER DATA. REMOVE NULLS FROM `CIFNO`. FILTER FOR         ***;
	*** `ENTDATE` FROM A YEAR AGO UNTIL MOST RECENT. KEEP ONLY     ***;
	*** NULLS FROM `POCD`. KEEP ONLY NULLS FROM `PLCD`. KEEP ONLY  ***;
    *** NULLS FROM `PLDATE`. KEEP ONLY NULLS FROM `POFFDATE`. KEEP ***;
	*** ONLY NULLS FROM `BNKRPTDATE`. KEEP RELEVANT `CLASSID`S AND ***;
	*** `OWNST`S ------------------------------------------------- ***;
	WHERE CIFNO NE "" & 
		ENTDATE >= "&_36MONTH" & 
		POCD = "" & 
		PLCD = "" & 
		PLDATE = "" & 
		POFFDATE = ""  & 
		BNKRPTDATE = "" & 
		CLASSID IN (10,19,20,31,34) & 
		OWNST IN ("AL", "GA", "NC", "NM", "OK", "SC", "TN", "TX", "VA", 
				  "MO", "WI");
	
	*** CREATE `SS7BRSTATE` VARIABLE ----------------------------- ***;
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2)); 
RUN;

*** READ IN DATA FROM `dw.vw_BORROWER` TABLE. SUBSET FOR       ***;
*** RELEVANT VARIABLES. FILTER TO ISOLATE XS LOANS. STORE AS       ***; 
*** `BORRNLS` DATASET -------------------------------------------- ***;
DATA BORRNLS;

	*** SET LENGTH FOR `FIRSTNAME`, `MIDDLENAME`, `LASTNAME` ----- ***;
	LENGTH FIRSTNAME $20 MIDDLENAME $20 LASTNAME $30;

	*** SUBSET `dw.vw_BORROWER` USING RELEVANT VARIABLES ----- ***;
	SET dw.vw_BORROWER(
		KEEP = RMC_UPDATED PHONE CELLPHONE CIFNO SSNO SSNO_RT7  FNAME 
			LNAME ADR1 ADR2 CITY STATE ZIP BRNO AGE CONFIDENTIAL
			SOLICIT CEASEANDDESIST CREDITSCORE);
	WHERE CIFNO NOT =: "B"; /* REMOVE `CIFNO`S THAT BEGIN WITH "B" */
	
	*** STRIP WHITE SPACE FROM `FNAME`, `LNAME`, `ADR1`, `ADR2`,   ***;
	*** `CITY`, `STATE`, `ZIP` ----------------------------------- ***;
	FNAME = STRIP(FNAME);
	LNAME = STRIP(LNAME);
	ADR1 = STRIP(ADR1);
	ADR2 = STRIP(ADR2);
	CITY = STRIP(CITY);
	STATE = STRIP(STATE);
	ZIP = STRIP(ZIP);
	
	*** FIND ALL INSTANCES OF "JR" IN `FNAME`. REMOVE "JR" FROM    ***;
	*** STRING AND STORE AS `FIRSTNAME`. STORE ALL OCCURENCES OF   ***;
	*** "JR" IN NEW VARIABLE, `SUFFIX` --------------------------- ***;
	if find(fname, " JR") ge 1 then do;
		firstname = tranwrd(fname, "JR", "");
		suffix = "JR";
	end;
	
	*** FIND ALL INSTANCES OF "SR" IN `FNAME`. REMOVE "SR" FROM    ***;
	*** STRING AND STORE AS `FIRSTNAME`. STORE ALL OCCURENCES OF   ***;
	*** "SR" IN NEW VARIABLE, `SUFFIX` --------------------------- ***;
	if find(fname, " SR") ge 1 then do;
		firstname = tranwrd(fname, "SR", "");
		suffix = "SR";
	end;
	
	*** IF `SUFFIX` IS NULL, TAKE 1ST WORD IN `FNAME` AND STORE AS ***;
	*** `FIRSTNAME`. TAKE 2ND, 3RD, AND 4TH WORDS IN `FNAME` AND   ***;
	*** STORE AS `MIDDLENAME` ------------------------------------ ***;
	IF SUFFIX = "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, 1);
		MIDDLENAME = CATX(" ", SCAN(FNAME, 2, " "), 
			SCAN(FNAME, 3, " "), SCAN(FNAME, 4, " "));
	END;
	NWORDS = COUNTW(FNAME, " "); /* COUNT # OF WORDS IN `FNAME` */
	
	*** IF MORE THAN 2 WORDS IN `FNAME`, TAKE 1ST WORD AND STORE IN***; 
	*** `FIRSTNAME`, AND TAKE SECOND WORD AND ADD TO `MIDDLENAME`  ***;
	IF NWORDS > 2 & SUFFIX NE "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, " ");
		MIDDLENAME = SCAN(FNAME, 2, " ");
	END;
	DOB = COMPRESS(AGE, "-"); /* REMOVE HYPHEN, STORE `AGE` AS `DOB` */
	LASTNAME = LNAME; /* STORE `LNAME` AS `LASTNAME` */
	*DROP FNAME LNAME NWORDS AGE; /* DROP VARIABLES FROM TABLE */
	IF CIFNO NE ""; /* FILTER SET OF NULL `CIFNO`S */

	*** STORE `SSNO` AS `SSNO1`. *STORE `SSNO_RT7` AS `SSNO1_RT7`  ***;
	SSNO1 = SSNO;
	SSNO1_RT7 = SSNO_RT7;
RUN;

*** SPLIT: GROUP BY `CIFNO` - APPLY: FIND MAX `ENTDATE` PER `CIFNO`***:
*** - COMBINE: STORE RECORDS WITH MAX `ENTDATE` PER `CIFNO` IN     ***;
*** `XS_LDEDUPED` TABLE ------------------------------------------ ***;
PROC SQL;
	CREATE TABLE XS_LDEDUPED AS
	SELECT *
	FROM XS_L
	GROUP BY CIFNO
	HAVING ENTDATE = MAX(ENTDATE);
QUIT;

*** REMOVE RECORDS WITH DUPLICATE `CIFNO` FROM `XS_LDEDUPED` ----- ***;
PROC SORT 
	DATA = XS_LDEDUPED NODUPKEY; 
	BY CIFNO; 
RUN;

*** SORT `BORRNLS` BY `CIFNO` DEFAULT ASCENDING THEN BY            ***;
*** `RMC_UPDATED` DESCENDING ------------------------------------- ***;
PROC SORT 
	DATA = BORRNLS; 
	BY CIFNO DESCENDING RMC_UPDATED; 
RUN;

*** REMOVE RECORDS WITH DUPLICATE `CIFNO` FROM `BORRNLS` --------- ***;
PROC SORT 
	DATA = BORRNLS OUT = BORRNLS2 NODUPKEY; 
	BY CIFNO; 
RUN;

*** MERGE `XS_LDEDUPED` AND `BORRNLS2` BY `CIFNO` AS `LOANNLSXS` - ***;
DATA LOANNLSXS;
	MERGE XS_LDEDUPED(IN = x) BORRNLS2(IN = y);
	BY CIFNO;
	IF x AND y;
RUN;

DATA XS; /* STACK ALL DW XS LOANS */
	SET LOANNLSXS;
RUN;

*** MERGE `XS` FROM OUR DW WITH INFO FROM TCI SITES TO IDENTIFY    ***;
*** MADE APPLICATIONS AND TO ID UNMADE APPLICATIONS -------------- ***;
PROC SORT 
	DATA = XS;
	BY SSNO1_RT7;
RUN;

PROC SORT 
	DATA = TCI;
	BY SSNO1_RT7;
RUN;

DATA TCI2MADES;
	SET TCI;
	DROP BRACCTNO;
RUN;

DATA MADES;
	MERGE XS(IN = x) TCI2MADES(IN = y);
	BY SSNO1_RT7;
	IF x = 1;
RUN;

DATA UNMADES;
	MERGE XS(IN = x) TCI(IN = y);
	BY SSNO1_RT7;
	IF x = 0 AND y = 1;
	MADE_UNMADE = "UNMADE";
RUN;

DATA UNMADES;
	SET UNMADES;
	RENAME 'DATE Submitted'n = DATE_SUBMITTED;
	APPLICATION_DATE = INPUT(STRIP('application DATE'n), mmddyy10.);
	FORMAT APPLICATION_DATE mmddyy10.;
RUN;

DATA UNMADES2;
	SET UNMADES (WHERE = (INTNX('MONTH', TODAY(), -6, 'b') <= 
		APPLICATION_DATE));
RUN;

*** FOR MATCHED, KEEP ONLY INFO FROM LOAN AND BORROWER TABLES ---- ***;
DATA MADES2;
	SET MADES;
	MADE_UNMADE = "MADE";
RUN;

*** APPEND MADES AND UNMADES FOR FULL XS UNIVERSE ---------------- ***;
DATA XSTOT; 
	SET UNMADES2 MADES2;
RUN;

DATA XSTOT;
	SET XSTOT;
	IF SS7BRSTATE = "" THEN SS7BRSTATE = CATS(SSNO1_RT7, 
		SUBSTR(OWNBR, 1, 2));
	IF CRSCORE < 625 THEN RISK_SEGMENT = "624 AND BELOW";
	IF 625 <= CRSCORE < 650 THEN RISK_SEGMENT = "625-649";
	IF 650 <= CRSCORE < 851 THEN RISK_SEGMENT = "650-850";
	IF CLASSID IN (10, 21, 31) THEN SOURCE_2 = "RETAIL";
	IF SOURCE = "TCIRetail" THEN SOURCE_2 = "RETAIL";
	IF CLASSID IN (13, 14, 19, 20, 32, 34, 40, 41, 45, 68, 69, 72, 75,
		78, 79, 80, 88, 89, 90) THEN SOURCE_2 = "AUTO";
	IF SOURCE = "TCICentral" THEN SOURCE_2 = "AUTO";
RUN;

DATA XS_TOTAL;
	LENGTH OFFER_SEGMENT $20;
	SET XSTOT;
	STATE = STRIP(STATE);
	IF CRSCORE = 0 THEN BADFICO_FLAG = "X";
	IF CRSCORE = . THEN BADFICO_FLAG = "X";
	IF CRSCORE > 725 THEN BADFICO_FLAG = "X";
	IF STATE = "NC" & 
	   MADE_UNMADE = "UNMADE" 
		THEN NCAUTOUN_FLAG = "X";
	IF STATE = "NC" & 
	   SOURCE_2 = "AUTO" & 
	   MADE_UNMADE = "MADE" 
		THEN OFFER_SEGMENT = "ITA";
	IF STATE IN ("GA", "VA") 
		THEN OFFER_SEGMENT = "ITA";
	IF STATE IN ("SC","TX","TN","AL","OK","NM", "MO", "WI") & 
	   SOURCE_2 = "AUTO" 
		THEN OFFER_SEGMENT = "ITA";
	IF STATE IN ("SC","NC","TX","TN","AL","OK","NM", "MO", "WI") & 
	   SOURCE_2 = "RETAIL" & 
	   RISK_SEGMENT = "624 AND BELOW" 
		THEN OFFER_SEGMENT = "ITA";
RUN;

*** DEDUPE XS ---------------------------------------------------- ***;
DATA XS_TOTAL;
	SET XS_TOTAL;
	IF OFFER_SEGMENT NE "ITA"; /* DROP ITA'S */
	CAMP_TYPE = "XS";
RUN;

*** STEP 1: PULL IN DATA FOR `FB`S ------------------------------- ***;
DATA LOAN_PULL; /* FROM LOAN TABLE FOR FB */
	SET dw.vw_loan_nlS (
		KEEP = PURCD CIFNO BRACCTNO ID OWNBR OWNST SSNO1_RT7 SSNO1
			   SSNO2 NETLOANAMOUNT LNAMT FINCHG SSNO1_RT7 LOANTYPE
			   ENTDATE LOANDATE CLASSID CLASSTRANSLATION
			   XNO_TRUEDUEDATE FIRSTPYDATE SRCD POCD POFFDATE PLCD
			   PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER DATEPAIDLAST
			   APRATE CRSCORE CURBAL SERCHG TILA_LNAMT);
	WHERE POFFDATE BETWEEN "&_36MONTH" AND "&_1DAY" & 
		  POCD = "13" & 
		  OWNST IN ("AL", "GA", "NC", "NM", "OK", "SC", "TN", "TX",
					"VA", "MO", "WI"); /* PAID OUT LOANS */
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	LOANDATE_SAS = INPUT(STRIP('LOANDATE'n), yymmdd10.);
	FORMAT LOANDATE_SAS yymmdd10.;
	DAYS_ON_BOOKS = TODAY() - LOANDATE_SAS;
	MOS_ON_BOOKS = ROUND(DAYS_ON_BOOKS / 30, 1.0);
RUN;

PROC SQL;
	CREATE TABLE LOAN1NLSFB AS
	SELECT *
	FROM LOAN_PULL
	GROUP BY CIFNO
	HAVING ENTDATE = MAX(ENTDATE);
QUIT;

PROC SORT 
	DATA = LOAN1NLSFB;
	BY CIFNO;
RUN;

DATA LOANNLSFB;
	MERGE LOAN1NLSFB(IN = x) BORRNLS2(IN = y);
	BY CIFNO;
	IF x AND y;
RUN;

DATA FB;
	SET LOANNLSFB;
	CAMP_TYPE = "FB";
RUN;

*** APPEND XS TO FB ---------------------------------------------- ***;
DATA MERGED_L_B_XS_FB;
	SET FB XS_TOTAL;
RUN;

PROC SORT 
	DATA = MERGED_L_B_XS_FB OUT = MERGED_L_B_XS_FB2 NODUPKEY;
	BY BRACCTNO;
RUN;

*** PULL IN INFORMATION FOR STATFLAGS ---------------------------  ***;
DATA STATFLAGS;
	SET dw.vw_loan(KEEP = OWNBR SSNO1_RT7 ENTDATE STATFLAGS Acctrefno);
	WHERE ENTDATE > "&_5YR" & 
		  STATFLAGS NE "";
RUN;

PROC SQL; /* IDENTIFYING BAD STATFLAGS */
 	CREATE TABLE STATFLAGS2 AS
	SELECT * 
	FROM STATFLAGS 
	WHERE STATFLAGS CONTAINS "4" OR STATFLAGS CONTAINS "5" OR
		  STATFLAGS CONTAINS "6" OR STATFLAGS CONTAINS "7" OR
		  STATFLAGS CONTAINS "A" OR STATFLAGS CONTAINS "B" OR
		  STATFLAGS CONTAINS "C" OR STATFLAGS CONTAINS "D" OR
		  STATFLAGS CONTAINS "I" OR STATFLAGS CONTAINS "J" OR
		  STATFLAGS CONTAINS "L" OR STATFLAGS CONTAINS "P" OR
		  STATFLAGS CONTAINS "R" OR STATFLAGS CONTAINS "V" OR
		  STATFLAGS CONTAINS "W" OR STATFLAGS CONTAINS "X" OR
		  STATFLAGS CONTAINS "S";
RUN;

*** TAGGING BAD STATFLAGS ---------------------------------------- ***;
DATA STATFLAGS2; 
	SET STATFLAGS2;
	STATFL_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE OWNBR SSNO1_RT7;
	RENAME STATFLAGS = STATFLAGS_OLD;
RUN;

PROC SORT 
	DATA = STATFLAGS2 NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B_XS_FB2;
	BY SS7BRSTATE;
RUN;

*** MERGE FILE WITH STATFLAG FLAGS ------------------------------- ***;
DATA MERGED_L_B2;
	MERGE MERGED_L_B_XS_FB2(IN = x) STATFLAGS2;
	BY SS7BRSTATE;
	IF x = 1;
RUN;

*** FLAG BANKRUPTCIES IN PAST 5 YEARS ---------------------------- ***;
DATA BK5YRDROPS;
	SET dw.vw_loan (
		KEEP = ENTDATE SSNO1_RT7 OWNBR BNKRPTDATE BNKRPTCHAPTER);
	WHERE ENTDATE > "&_5YR";
RUN;

DATA BK5YRDROPS;
	SET BK5YRDROPS;
	WHERE BNKRPTCHAPTER > 0 | BNKRPTDATE NE "";
RUN;

DATA BK5YRDROPS;
	SET BK5YRDROPS;
	BK5_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP BNKRPTDATE ENTDATE SSNO1_RT7 OWNBR BNKRPTCHAPTER;
RUN;

PROC SORT 
	DATA = BK5YRDROPS NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) BK5YRDROPS;
	BY SS7BRSTATE;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	IF BNKRPTDATE NE "" THEN BK5_FLAG = "X";
	IF BNKRPTCHAPTER NOT IN (0, .) THEN BK5_FLAG = "X";
RUN;

*** FLAG BAD TRW STATUS ------------------------------------------ ***;
DATA TRWSTATUS_FL; /* FIND FROM 5 YEARS BACK */
	SET dw.vw_loan(KEEP = OWNBR SSNO1_RT7 ENTDATE TRWSTATUS);
	WHERE ENTDATE > "&_5YR" & TRWSTATUS NE "";
RUN;

DATA TRWSTATUS_FL; /* FLAG FOR BAD TRW'S */ 
	SET TRWSTATUS_FL;
	TRW_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE SSNO1_RT7 OWNBR;
RUN;

PROC SORT 
	DATA = TRWSTATUS_FL NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2; /* MERGE PULL WITH TRW FLAGS */
	MERGE MERGED_L_B2(IN = x) TRWSTATUS_FL;
	BY SS7BRSTATE;
	IF x;
RUN;

*** IDENTIFY BAD PO CODES ---------------------------------------- ***;
DATA PO_CODES_3YR;
	SET dw.vw_loan(KEEP = ENTDATE POCD SSNO1_RT7 OWNBR);
	WHERE ENTDATE > "&_3YR" & POCD IN ("49", "50", "61", "62", "63",
									   "64", "66", "68", "93", "97");
RUN;

DATA PO_CODES_3YR;
	SET PO_CODES_3YR;
	BADPOCODE_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE POCD SSNO1_RT7 OWNBR;
RUN;

PROC SORT 
	DATA = PO_CODES_3YR NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) PO_CODES_3YR;
	BY SS7BRSTATE;
	IF x;
RUN;

DATA PO_CODES_FOREVER;
	SET dw.vw_loan(KEEP = ENTDATE POCD SSNO1_RT7 OWNBR);
	WHERE POCD IN ("21", "94", "95", "96");
RUN;

DATA PO_CODES_FOREVER;
	SET PO_CODES_FOREVER;
	DECEASED_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE POCD SSNO1_RT7 OWNBR;
RUN;

PROC SORT 
	DATA=PO_CODES_FOREVER NODUPKEY;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) PO_CODES_FOREVER;
	BY SS7BRSTATE;
	IF x;
RUN;

DATA CON1YR_FL; /* FIND FROM 2 YEARS BACK */
	SET dw.vw_loan(KEEP = OWNBR SSNO1_RT7 ENTDATE CONPROFILE1);
	WHERE ENTDATE > "&_15MONTH" & CONPROFILE1 NE "";
	DATA CON1YR_FL; /* FLAG FOR CON5 */
	SET CON1YR_FL;
	_60 = COUNTC(CONPROFILE1, "2");
	_90 = COUNTC(CONPROFILE1, "3");
	_120A = COUNTC(CONPROFILE1, "4");
	_120B = COUNTC(CONPROFILE1, "5");
	_120C = COUNTC(CONPROFILE1, "6");
	_120D = COUNTC(CONPROFILE1, "7");
	_120E = COUNTC(CONPROFILE1,"8");
	_90PLUS = SUM(_90, _120A, _120B, _120C, _120D, _120E);
	IF _60 > 1 | _90PLUS > 0 THEN CON1YR_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	/*DROP ENTDATE SSNO1_RT7 OWNBR CONPROFILE1;*/
RUN;

DATA CON1YR_FL_2;
	SET CON1YR_FL;
	IF CON1YR_FLAG = "X";
RUN;

PROC SORT 
	DATA = CON1YR_FL_2 NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2; /* MERGE PULL WITH CON5 FLAGS */
	MERGE MERGED_L_B2(IN = x) CON1YR_FL_2;
	BY SS7BRSTATE;
	IF x;
RUN;

*** IDENTIFY IF CUSTOMER CURRENTLY HAS AN OPEN LOAN FOR FB ------- ***;
DATA OPENLOANS;
	SET dw.vw_loan(
		KEEP = SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "";
RUN;

DATA SSNO2S;
	SET OPENLOANS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS1;
	SET OPENLOANS SSNO2S;
RUN;

DATA OPENLOANS1;
	SET OPENLOANS1;
	OPEN_FLAG = "X";
	DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;

PROC SORT 
	DATA = OPENLOANS1 NODUPKEY;
	BY SSNO1_RT7;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SSNO1_RT7;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) OPENLOANS1;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	IF CAMP_TYPE = "XS" THEN OPEN_FLAG = "";
RUN;

*** IDENTIFY IF CUSTOMER CURRENTLY HAS AN OPEN LOAN FOR XS UNMADE  ***;
DATA OPENLOANSXS;
	SET dw.vw_loan(
		KEEP = SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "";
RUN;

DATA SSNO2S2;
	SET OPENLOANSXS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS1XS;
	SET OPENLOANSXS SSNO2S2;
RUN;

DATA OPENLOANS1XS;
	SET OPENLOANS1XS;
	OPEN_FLAG = "X";
	DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;

PROC SORT 
	DATA = OPENLOANS1XS NODUPKEY;
	BY SSNO1_RT7;
RUN;

DATA UNMADESDROP MERGED_L_B3;
	SET MERGED_L_B2;
	IF MADE_UNMADE = "UNMADE" THEN OUTPUT UNMADESDROP;
	ELSE OUTPUT MERGED_L_B3;
RUN;

PROC SORT 
	DATA = UNMADESDROP;
	BY SSNO1_RT7;
RUN;

DATA UNMADESDROP;
	MERGE UNMADESDROP(IN = x) OPENLOANS1XS;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B3 UNMADESDROP;
RUN;

DATA OPENLOANS2;
	SET dw.vw_loan(
		KEEP = OWNBR SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE
			   BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "";
RUN;

DATA SSNO2S;
	SET OPENLOANSXS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS3;
	SET OPENLOANS2 SSNO2S;
RUN;

DATA OPENLOANS4;
	SET OPENLOANS3;
	OPEN_FLAG2 = "X";
	DROP POCD SSNO2 OWNBR PLCD POFFDATE PLDATE BNKRPTDATE;
RUN;

PROC SORT 
	DATA = OPENLOANS4;
	BY SSNO1_RT7;
RUN;

DATA ONE_OPEN MULT_OPEN;
	SET OPENLOANS4;
	BY SSNO1_RT7;
	IF FIRST.SSNO1_RT7 AND LAST.SSNO1_RT7 THEN OUTPUT ONE_OPEN;
	ELSE OUTPUT MULT_OPEN;
RUN;

PROC SORT 
	DATA = MULT_OPEN NODUPKEY;
	BY SSNO1_RT7;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SSNO1_RT7;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) MULT_OPEN;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA OPENLOANSXS2;
	SET dw.vw_loan(
		KEEP = CLASSTRANSLATION SSNO2 SSNO1_RT7 POCD PLCD POFFDATE
			   PLDATE BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "" & 
		  CLASSTRANSLATION NOT IN ("Retail", "AUTO-I", "AUTO-D");
RUN;

DATA SSNO2S2;
	SET OPENLOANSXS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS1XS;
	SET OPENLOANSXS2 SSNO2S2;
RUN;

DATA OPENLOANS1XS2;
	SET OPENLOANS1XS;
	OPEN_FLAG3 = "X";
	DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;

PROC SORT 
	DATA=OPENLOANS1XS2 NODUPKEY;
	BY SSNO1_RT7;
RUN;

DATA XSPERSONALDROP MERGED_L_B4;
	SET MERGED_L_B2;
	IF CAMP_TYPE = "XS" THEN OUTPUT XSPERSONALDROP;
	ELSE OUTPUT MERGED_L_B4;
RUN;

PROC SORT 
	DATA = XSPERSONALDROP;
	BY SSNO1_RT7;
RUN;

DATA XSPERSONALDROP;
	MERGE XSPERSONALDROP(IN = x) OPENLOANS1XS2;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B4 XSPERSONALDROP;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	IF OPEN_FLAG3 = "X" THEN OPEN_FLAG2 = "X";
RUN;

*** FLAG NULL DOB                                                  ***;
*** FIND STATES OUTSIDE OF FOORPRINT                               ***;
*** FLAG DNS DNH                                                   ***;
*** FLAG NONMATCHING BRANCH STATE AND BORROWER STATE               ***;
*** FLAG BAD SSNS                                                  ***;
*** FLAG INCOMPLETE INFO                                           ***;
*** FLAG BAD BRANCHES -------------------------------------------- ***;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	ADR1 = STRIP(ADR1);
	ADR2 = STRIP(ADR2);
	CITY = STRIP(CITY);
	STATE = STRIP(STATE);
	ZIP = STRIP(ZIP);
	CONFIDENTIAL = STRIP(CONFIDENTIAL);
	SOLICIT = STRIP(SOLICIT);
	FIRSTNAME = COMPRESS(FIRSTNAME, '1234567890!@#$^&*()''"%');
	LASTNAME = COMPRESS(LASTNAME, '1234567890!@#$^&*()''"%');
	IF INDEX(FIRSTNAME, """") > 0 THEN NAME_DELETEFLAG = "X";
	IF INDEX(LASTNAME, """") > 0 THEN NAME_DELETEFLAG = "X";
	IF INDEX(FIRSTNAME, "''") > 0 THEN NAME_DELETEFLAG = "X";
	IF INDEX(LASTNAME, "''") > 0 THEN NAME_DELETEFLAG = "X";
	IF COUNTC(LASTNAME, " ", 'iv') < 2 THEN NAME_DELETEFLAG = "X";
	IF ADR1 = "" THEN ADR1 = ADR2;

	*** FLAG INCOMPLETE INFO ------------------------------------- ***;
	IF ADR1 = "" THEN MISSINGINFO_FLAG = "X"; 
	IF STATE = "" THEN MISSINGINFO_FLAG = "X"; 
	IF FIRSTNAME = "" THEN MISSINGINFO_FLAG = "X";   
	IF LASTNAME = "" THEN MISSINGINFO_FLAG = "X";
	IF LASTNAME = "NULL" THEN MISSINGINFO_FLAG = "X";
	IF ZIP = "" THEN MISSINGINFO_FLAG = "X";

	*** FLAG INCOMPLETE DOB -------------------------------------- ***;
	IF DOB = "" THEN NULLDOB_FLAG = "X";
	IF OWNBR IN ("1", "0001", "198", "0198", "398", "0398", "498", 
				 "0498", "600", "0600", "698", "0698", 
				 "898", "0898", "9000", "9000") 
		THEN BADBRANCH_FLAG = "X";
	IF SUBSTR(OWNBR, 3, 2) = "99" THEN BADBRANCH_FLAG = "X";
	
	*** FIND STATES OUTSIDE OF FOOTPRINT ------------------------- ***;
	IF STATE NOT IN ("AL", "GA", "NC", "NM", "OK", "SC", "TN", "TX", 
					 "VA", "MO", "WI") THEN OOS_FLAG = "X";
	
	*** FLAG CONFIDENTIAL ---------------------------------------- ***;
	IF CONFIDENTIAL = "Y" THEN DNS_DNH_FLAG = "X"; 
	IF SOLICIT = "N" THEN DNS_DNH_FLAG = "X"; /* FLAG DNS */
	IF CEASEANDDESIST = "Y" THEN DNS_DNH_FLAG = "X"; /* FLAG CANDD */
	IF SSNO1 = "" THEN SSNO1 = SSNO;
	IF SSNO1 =: "99" THEN BADSSN_FLAG = "X"; /* FLAG BAD SSNS */
	IF SSNO1 =: "98" THEN BADSSN_FLAG = "X"; /* FLAG BAD SSNS */
	CON_RECENT3 = SUBSTR(CONPROFILE1, 1, 3);
	CON_RECENT4TO6 = SUBSTR(CONPROFILE1, 4, 3);
	CON_RECENT6 = SUBSTR(CONPROFILE1, 1, 6);
	_30_RECENT3 = COUNTC(CON_RECENT3, "1");
	_30_RECENT4TO6 = COUNTC(CON_RECENT4TO6, "1");
	_30_RECENT6 = COUNTC(CON_RECENT6, "1");
	_60_RECENT6 = COUNTC(CON_RECENT6, "2");
	_30 = COUNTC(CONPROFILE1, "1");
	_60 = COUNTC(CONPROFILE1, "2");
	_90 = COUNTC(CONPROFILE1, "3");
	_120A = COUNTC(CONPROFILE1, "4");
	_120B = COUNTC(CONPROFILE1, "5");
	_120C = COUNTC(CONPROFILE1, "6");
	_120D = COUNTC(CONPROFILE1, "7");
	_120E = COUNTC(CONPROFILE1, "8");
	_90PLUS = SUM(_90, _120A, _120B, _120C, _120D, _120E);
	IF _30 > 3 | _60 > 1 | _90PLUS > 0 | _60_RECENT6 > 0 | 
	   _30_RECENT3 > 1 | _30_RECENT6 > 2 
		THEN CONPROFILE_FLAG = "X";
	_9S = COUNTC(CONPROFILE1, "9");
	IF _9S > 10 THEN LESSTHAN2_FLAG = "X";
	XNO_TRUEDUEDATE2 = INPUT(SUBSTR(XNO_TRUEDUEDATE, 6, 2) || '/' || 
							 SUBSTR(XNO_TRUEDUEDATE, 9, 2) || '/' || 
							 SUBSTR(XNO_TRUEDUEDATE, 1, 4), mmddyy10.);
	FORMAT XNO_TRUEDUEDATE2 mmddyy10.;
	FIRSTPYDATE2 = INPUT(SUBSTR(FIRSTPYDATE, 6, 2) || '/' || 
						 SUBSTR(FIRSTPYDATE, 9, 2) || '/' ||
						 SUBSTR(FIRSTPYDATE, 1, 4), mmddyy10.);
	FORMAT FIRSTPYDATE2 mmddyy10.;
	PMT_DAYS = XNO_TRUEDUEDATE2 - FIRSTPYDATE2;
	IF PMT_DAYS < 60 THEN LESSTHAN2_FLAG = "X";
	IF PMT_DAYS = . & _9S < 10 THEN LESSTHAN2_FLAG = "";
	IF PMT_DAYS > 59 & _9S > 10 THEN LESSTHAN2_FLAG = "";
	IF PLAMT > 5 THEN PLAMT_FLAG = "X";

	IF CAMP_TYPE = "FB" THEN DO;
		
		*** FLAG NONMATCHING BRANCH STATE AND BORROWER STATE ----- ***;
		IF OWNST NE STATE THEN STATE_MISMATCH_FLAG = "X";
		LESSTHAN2_FLAG = ""; /*MAKE SURE FB FLAG IS SET TO NULL */
	END;

	IF PURCD IN ("020", "015", "016", "021", "022") 
		THEN DLQREN_FLAG = "X";

	IF OWNBR = "0251" THEN OWNBR = "0580";
	IF OWNBR = "0252" THEN OWNBR = "0683";
	IF OWNBR = "0253" THEN OWNBR = "0581";
	IF OWNBR = "0254" THEN OWNBR = "0582";
	IF OWNBR = "0255" THEN OWNBR = "0583";
	IF OWNBR = "0256" THEN OWNBR = "1103";
	IF OWNBR = "0302" THEN OWNBR = "0133";
	IF OWNBR = "1016" THEN OWNBR = "1008";
	IF OWNBR = "0877" THEN OWNBR = "0806";
	IF OWNBR = "0159" THEN OWNBR = "0132";
	IF OWNBR = "0152" THEN OWNBR = "0115";
	IF OWNBR = "0885" THEN OWNBR = "0802";
	IF ZIP =: "29659" & OWNBR = "0152" THEN OWNBR = "0121";
	IF ZIP =: "36264" & OWNBR = "0877" THEN OWNBR = "0870";
	IF OWNBR = "1003" AND ZIP =: "87112" THEN OWNBR = "1013";
	IF OWNBR = "0872" THEN OWNBR = "0807";
	IF OWNBR = "0668" THEN OWNBR = "0680";

	IF "&_18MONTH" <= POFFDATE < "&_15MONTH" THEN _18MTH_SWAPIN = "X";
	IF "&_24MONTH" <= POFFDATE < "&_18MONTH" THEN _24MTH_SWAPIN = "X";
	IF "&_30MONTH" <= POFFDATE < "&_24MONTH" THEN _30MTH_SWAPIN = "X";
	IF "&_36MONTH" <= POFFDATE < "&_30MONTH" THEN _36MTH_SWAPIN = "X";
	IF PURCD = "011" THEN PURCD_SWAPIN = "X";
	
	/*COVID*/
	/*
	IF CAMP_TYPE = "XS" THEN DELETE;
	IF OWNST = "NM" THEN DELETE;
	*/
	/*Tiger King Branches    */
	
	IF OWNBR = "0415" THEN BADBRANCH_FLAG = "X";
	IF OWNBR = "0585" THEN BADBRANCH_FLAG = "X";
	IF OWNBR = "1011" THEN BADBRANCH_FLAG = "X";
	IF OWNBR = "1012" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0504" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0518" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0923" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "1010" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0521" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0537" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0586" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0589" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0904" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0910" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0915" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0917" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0918" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "0921" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "1001" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "1002" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "1007" THEN BADBRANCH_FLAG = "X";
	*IF OWNBR = "1014" THEN BADBRANCH_FLAG = "X";  
RUN;

**********************************************************************;
**********************************************************************;
**********************************************************************;
data MERGED_L_B2;
	SET MERGED_L_B2;
	FULLADDRESS = catx(',', ADR1, ADR2, CITY, STATE, ZIP);
run;

PROC SORT 
	DATA = MERGED_L_B2;
	BY descending CRSCORE descending CURBAL descending POffDate;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY FULLADDRESS;
RUN;

data MERGED_L_B2;
	SET MERGED_L_B2;
	by FULLADDRESS; 
	DUPADDRESS_FLAG = 'X';
	if first.FULLADDRESS then DUPADDRESS_FLAG = ''; 
run;

**********************************************************************;
**********************************************************************;
**********************************************************************;

*** PULL AND MERGE DLQ INFO FOR FB'S ----------------------------- ***;
PROC FORMAT;
	VALUE CDFMT 1 = 'Current' 
				2 = '1-29CD'
				3 = '30-59CD'
				4 = '60-89CD'
				5 = '90-119CD'
				6 = '120-149CD'
				7 = '150-179CD'
				8 = '180+CD'
				OTHER = ' ';
RUN;

DATA TEMP;
	SET dw.vw_loan(
		KEEP = BRACCTNO SRCD ENTDATE POFFDATE POCD CLASSTRANSLATION
			   LNAMT CONPROFILE1 BRTRFFG SSNO1_RT7 
		WHERE = (POCD = '13' AND POFFDATE > "&_36MONTH"));
	
	ENTDT = INPUT(SUBSTR(ENTDATE, 6, 2) || '/' || 
				  SUBSTR(ENTDATE, 9, 2) || '/' ||
				  SUBSTR(ENTDATE, 1, 4), mmddyy10.);
	format ENTDT mmddyy10.;
	PODT = INPUT(SUBSTR(POFFDATE, 6, 2) || '/' ||
				 SUBSTR(POFFDATE, 9, 2) || '/' ||
				 SUBSTR(POFFDATE, 1, 4), mmddyy10.);
	format PODT mmddyy10.;
	IF POFFDATE > "&_1DAY" THEN DELETE;/*
	IF PUT(ENTDT, yymmn6.) = PUT(PODT, yymmn6.) THEN DELETE;
	*/
	DROP POFFDATE ENTDATE POCD SRCD;
RUN; 

PROC SORT 
	NODUPKEY; 
	BY BRACCTNO; 
RUN;

DATA ATB_1;
	SET dw.vw_AgedTrialBalance(
		KEEP = LoanNumber Age2 BOM RUNDATE);
	AGE2 = Age2;
	YEARMONTH = BOM;
	BRACCTNO = LoanNumber;
	POACCTNO = BRACCTNO * 1;
	
	ATBDT = INPUT(SUBSTR(YEARMONTH, 6, 2) || '/' ||
				  SUBSTR(YEARMONTH, 9, 2) || '/' ||
				  SUBSTR(YEARMONTH, 1, 4), mmddyy10.);
	format ATBDT mmddyy10.;
	IF AGE2 =: '1' THEN AGE2 = '1.Current';
	KEEP ATBDT AGE2 BRACCTNO BOM RunDate;
RUN;

DATA ATB_2;
	SET dw.vw_ATB_Data(
		KEEP = BRACCTNO Age2 YEARMONTH);
	AGE2 = Age2;
	YEARMONTH = YEARMONTH;
	BRACCTNO = BRACCTNO;
	POACCTNO = BRACCTNO * 1;
	
	ATBDT = INPUT(SUBSTR(YEARMONTH, 6, 2) || '/' ||
				  SUBSTR(YEARMONTH, 9, 2) || '/' ||
				  SUBSTR(YEARMONTH, 1, 4), mmddyy10.);
	format ATBDT mmddyy10.;
	IF AGE2 =: '1' THEN AGE2 = '1.Current';
	KEEP ATBDT AGE2 BRACCTNO;
RUN;

DATA ATB;
	SET ATB_1 ATB_2;
	IF ATBDT = '.' THEN DELETE;
RUN;

PROC SORT 
	NODUPKEY; 
	BY BRACCTNO descending ATBDT; 
RUN;

DATA TEMP;
	MERGE TEMP(IN = a) ATB(IN = b);
	BY BRACCTNO;
	IF a;
	CD = SUBSTR(AGE2, 1, 1) * 1;
	AGE = INTCK('MONTH', ATBDT, PODT);
	IF AGE = 1 THEN DELQ1 = CD;
	ELSE IF AGE = 2 THEN DELQ2 = CD;
	ELSE IF AGE = 3 THEN DELQ3 = CD;
	ELSE IF AGE = 4 THEN DELQ4 = CD;
	ELSE IF AGE = 5 THEN DELQ5 = CD;
	ELSE IF AGE = 6 THEN DELQ6 = CD;
	ELSE IF AGE = 7 THEN DELQ7 = CD;
	ELSE IF AGE = 8 THEN DELQ8 = CD;
	ELSE IF AGE = 9 THEN DELQ9 = CD;
	ELSE IF AGE =10 THEN DELQ10 = CD;
	ELSE IF AGE =11 THEN DELQ11 = CD;
	ELSE IF AGE =12 THEN DELQ12 = CD;
	ELSE IF AGE =13 THEN DELQ13 = CD;
	ELSE IF AGE =14 THEN DELQ14 = CD;
	ELSE IF AGE =15 THEN DELQ15 = CD;
	ELSE DELETE;
	
	*** IF CD IS GREATER THAN 30-59 DAYS LATE, SET CD60 TO 1 ----- ***;
	IF CD > 3 THEN CD60 = 1;

	*** IF CD IS GREATER THAN 1-29 DAYS LATE, SET CD30 TO 1 ------ ***;
	IF CD > 2 THEN CD30 = 1;

	IF AGE < 4 THEN DO;
		IF CD > 2 THEN RECENT3 = 1; /* 30-59S IN LAST 6 MONTHS */
	END;

	ELSE IF 3 < AGE < 7 THEN DO;
		IF CD > 2 THEN RECENT4TO6 = 1; /* 30-59S 7 TO 12 MONTHS AGO */
	END;

	IF AGE < 7 THEN DO;
		IF CD > 2 THEN RECENT6 = 1; /* 30-59S IN LAST 6 MONTHS */
		IF CD > 3 THEN RECENT6_60 = 1;
	END;

	ELSE IF 6 < AGE < 16 THEN DO;
		IF CD > 2 THEN FIRST6 = 1; /* 30-59S 7 TO 12 MONTHS AGO */
		IF CD > 3 THEN FIRST6_60 = 1;
	END;

	KEEP CLASSTRANSLATION BRACCTNO DELQ1-DELQ12 CD CD30 CD60 AGE2 ATBDT
		 AGE RECENT3 RECENT4TO6 RECENT6_60 FIRST6_60 FIRST6 RECENT6;
RUN;

DATA TEMP2;
	SET TEMP;
	
	*** COUNT THE NUMBER OF 30-59S IN THE LAST YEAR WHEN FB HAD    ***;
	*** OPEN LOAN ------------------------------------------------ ***;
	LAST12 = SUM(RECENT6, FIRST6);
	LAST12_60 = SUM(RECENT6_60, FIRST6_60);
RUN;

PROC SUMMARY 
	DATA = TEMP2 NWAY MISSING;
	CLASS CLASSTRANSLATION BRACCTNO;
	VAR DELQ1-DELQ12 RECENT6 LAST12 FIRST6 RECENT6_60 LAST12_60
		FIRST6_60 RECENT3 RECENT4TO6 CD60 CD30;
	OUTPUT OUT = FINALFB(DROP = _TYPE_ _FREQ_) SUM = ;
RUN; 

DATA FBDLQ;
	SET FINALFB;
	TIMES30 = CD30;
	IF TIMES30 = . THEN TIMES30 = 0;
	IF RECENT6 = . THEN RECENT6 = 0;
	IF FIRST6 = . THEN FIRST6 = 0;
	IF LAST12 = . THEN LAST12 = 0;
	IF RECENT6_60 = . THEN RECENT6_60 = 0;
	IF FIRST6_60 = . THEN FIRST6_60 = 0;
	IF LAST12_60 = . THEN LAST12_60 = 0;
	IF RECENT3 = . THEN RECENT3 = 0;
	IF RECENT4TO6 = . THEN RECENT4TO6 = 0;
	DROP CD30;
	FORMAT DELQ1-DELQ15 CDFMT.;
RUN;

PROC SORT 
	DATA = FBDLQ NODUPKEY;
	BY BRACCTNO;
RUN;

DATA FB;
	SET MERGED_L_B2;
	IF CAMP_TYPE = "FB";
RUN;

PROC SORT 
	DATA = FB; /* SORT TO MERGE */
	BY BRACCTNO;
RUN;

DATA FBWITHDLQ; *MERGE PULL AND DQL INFORMATION;
	MERGE FB(IN = x) FBDLQ(IN = y);
	BY BRACCTNO;
	IF x = 1;
RUN;

**********************************************************************;
**********************************************************************;
**********************************************************************;
**********************************************************************;
**********************************************************************;

DATA ATB; 
	SET dw.vw_AgedTrialBalance(
		KEEP=LoanNumber Age2 BOM 
		WHERE=(BOM between "&_36MONTH" AND "&_1DAY"));
	BRACCTNO = LoanNumber;
	AGE2 = Age2;
	YEARMONTH = BOM;
RUN;

PROC SORT 
	DATA=ATB; *SORT TO MERGE;
	BY BRACCTNO;
RUN;

DATA NLS_POFF; 
	SET dw.vw_Loan_NLS(
		KEEP = BRACCTNO POFFDATE);
RUN;

PROC SORT 
	DATA = NLS_POFF; *SORT TO MERGE;
	BY BRACCTNO;
RUN;

DATA ATB_TEMP;
	MERGE ATB(IN = x) NLS_POFF(IN = y);
	BY BRACCTNO;
	IF y = x;
RUN;

DATA ATB;
	SET ATB_TEMP;
	ATBDT = INPUT(SUBSTR(YEARMONTH, 6, 2) || '/' ||
				  SUBSTR(YEARMONTH, 9, 2) || '/' ||
				  SUBSTR(YEARMONTH, 1, 4), mmddyy10.);
	FORMAT ATBDT mmddyy10.;
	PODT = INPUT(SUBSTR(POFFDATE, 6, 2) || '/' ||
				 SUBSTR(POFFDATE, 9, 2) || '/' ||
				 SUBSTR(POFFDATE, 1, 4), mmddyy10.);
	FORMAT PODT mmddyy10.;
	AGE_OPEN = INTCK('MONTH', ATBDT, "&SySDATE"d);
	AGE_CLOSED = INTCK('MONTH', ATBDT, PODT);
	CD = SUBSTR(AGE2, 1, 1) * 1;
	IF AGE_OPEN = 1 OR AGE_CLOSED = 1 THEN DELQ1 = CD;
	ELSE IF AGE_OPEN = 2 OR AGE_CLOSED = 2 THEN DELQ2 = CD;
	ELSE IF AGE_OPEN = 3 OR AGE_CLOSED = 3 THEN DELQ3 = CD;
	ELSE IF AGE_OPEN = 4 OR AGE_CLOSED = 4 THEN DELQ4 = CD;
	ELSE IF AGE_OPEN = 5 OR AGE_CLOSED = 5 THEN DELQ5 = CD;
	ELSE IF AGE_OPEN = 6 OR AGE_CLOSED = 6 THEN DELQ6 = CD;
	ELSE IF AGE_OPEN = 7 OR AGE_CLOSED = 7 THEN DELQ7 = CD;
	ELSE IF AGE_OPEN = 8 OR AGE_CLOSED = 8 THEN DELQ8 = CD;
	ELSE IF AGE_OPEN = 9 OR AGE_CLOSED = 9 THEN DELQ9 = CD;
	ELSE IF AGE_OPEN =10 OR AGE_CLOSED = 10 THEN DELQ10= CD;
	ELSE IF AGE_OPEN =11 OR AGE_CLOSED = 11 THEN DELQ11= CD;
	ELSE IF AGE_OPEN =12 OR AGE_CLOSED = 12 THEN DELQ12= CD;
	ELSE IF AGE_OPEN =13 OR AGE_CLOSED = 13 THEN DELQ13= CD;
	ELSE IF AGE_OPEN =14 OR AGE_CLOSED = 14 THEN DELQ14= CD;
	ELSE IF AGE_OPEN =15 OR AGE_CLOSED = 15 THEN DELQ15= CD;
	*** IF CD IS GREATER THAN 30-59 DAYS LATE, SET CD60 TO 1 ----- ***;
	IF CD > 3 THEN CD60 = 1; 
	*** IF CD IS GREATER THAN 1-29 DAYS LATE, SET CD30 TO 1 ------ ***;
	IF CD > 2 THEN CD30 = 1; 
	IF AGE_OPEN < 4 OR AGE_CLOSED < 4 THEN DO;
		IF CD > 2 THEN RECENT3 = 1; *NOTE 30-59S IN LAST Six MONTHS;
	END;
	ELSE IF 3 < AGE_OPEN < 7 OR 3 < AGE_CLOSED < 7 THEN DO;
		*** NOTE 30-59S FROM 7 TO 12 MONTHS AGO ------------------ ***;
		IF CD > 2 THEN RECENT4TO6 = 1; 
	END;
	IF AGE_OPEN < 7 OR AGE_CLOSED < 7 THEN DO;
		IF CD > 2 THEN RECENT6 = 1; *NOTE 30-59S IN LAST Six MONTHS;
		IF CD > 3 THEN RECENT6_60 = 1;
	END;
	ELSE IF 6 < AGE < 16 OR 6 < AGE_CLOSED < 16 THEN DO;
		*** NOTE 30-59S FROM 7 TO 15 MONTHS AGO ------------------ ***;
		IF CD > 2 THEN FIRST6 = 1;
		IF CD > 3 THEN FIRST6_60 = 1;
	END;
	KEEP BRACCTNO DELQ1-DELQ15 CD CD30 CD60 AGE2 ATBDT AGE_OPEN
		 AGE_CLOSED RECENT3 RECENT4TO6 RECENT6_60 FIRST6_60 FIRST6
		 RECENT6;
RUN;
/*


*STEP 14:  PULL AND MERGE DLQ INFO FOR XS'S;

DATA ATB; 
   SET ATB_TEMP;   
   ATBDT = INPUT(SUBSTR(YEARMONTH,6,2)||'/'||SUBSTR(YEARMONTH,9,2)||'/'||SUBSTR(YEARMONTH,1,4),mmddyy10.);     
   AGE = INTCK('MONTH',ATBDT,"&SySDATE"d);
CD = SUBSTR(AGE2,1,1)*1;   
 *i.e. FOR AGE=1: thIS IS moSt RECENT MONTH. Fill DELQ1, which IS DELQ FOR MONTH 1, WITH DELQ STATUS (CD);
   IF      AGE = 1 THEN DELQ1 = CD;
   ELSE IF AGE = 2 THEN DELQ2 = CD;
   ELSE IF AGE = 3 THEN DELQ3 = CD;
   ELSE IF AGE = 4 THEN DELQ4 = CD;
   ELSE IF AGE = 5 THEN DELQ5 = CD;
   ELSE IF AGE = 6 THEN DELQ6 = CD;
   ELSE IF AGE = 7 THEN DELQ7 = CD;
   ELSE IF AGE = 8 THEN DELQ8 = CD;
   ELSE IF AGE = 9 THEN DELQ9 = CD;
   ELSE IF AGE =10 THEN DELQ10= CD;
   ELSE IF AGE =11 THEN DELQ11= CD;
   ELSE IF AGE =12 THEN DELQ12= CD;
   IF CD>3 THEN CD60 = 1; *IF CD IS GREATER THAN 30-59 DAYS LATE, SET CD60 TO 1;
   IF CD>2 THEN CD30 = 1; *IF CD IS GREATER THAN 1-29 DAYS LATE, SET CD30 TO 1;
      IF AGE<4 THEN DO;
		IF CD>2 THEN RECENT3=1; *NOTE 30-59S IN LAST Six MONTHS;
		END;
		ELSE IF 3<AGE<7 THEN DO;
		IF CD>2 THEN RECENT4TO6=1; *NOTE 30-59S FROM 7 TO 12 MONTHS AGO;
		END;
   IF AGE<7 THEN DO;
		IF CD>2 THEN RECENT6=1; *NOTE 30-59S IN LAST Six MONTHS;
		IF CD>3 THEN RECENT6_60=1;
		END;
		ELSE IF 6<AGE<13 THEN DO;
		IF CD>2 THEN FIRST6=1; *NOTE 30-59S FROM 7 TO 12 MONTHS AGO;
		IF CD>3 THEN FIRST6_60=1;
		END;
		KEEP BRACCTNO DELQ1-DELQ12 CD CD30 CD60 AGE2 ATBDT AGE RECENT3 RECENT4TO6 RECENT6_60 FIRST6_60 FIRST6 RECENT6;
RUN;
*/

DATA ATB2;
	SET ATB;
	LAST12 = SUM(RECENT6, FIRST6); *COUNT THE NUMBER OF 30-59S IN THE LAST YEAR;
	LAST12_60 = SUM(RECENT6_60, FIRST6_60);
RUN;

*** COUNT CD30, CD60, RECENT6, FIRST6 BY BRACCTNO                  ***;
*** RECALL LOAN POTENTIALLY COUNTED FOR EACH MONTH --------------- ***;
PROC SUMMARY 
	DATA = ATB2 NWAY MISSING;
	CLASS BRACCTNO;
	VAR DELQ1-DELQ15 RECENT6 LAST12 FIRST6 RECENT6_60 LAST12_60
		FIRST6_60 RECENT3 RECENT4TO6 CD60 CD30;
	OUTPUT OUT = FINALXS(DROP = _TYPE_ _FREQ_) SUM =;
RUN;

DATA ATB4; /* CREATE NEW COUNTER VARIABLES */
	SET FINALXS;
	TIMES30 = CD30;
	IF TIMES30 = . THEN TIMES30 = 0;
	IF RECENT6 = . THEN RECENT6 = 0;
	IF FIRST6 = . THEN FIRST6 = 0;
	IF LAST12 = . THEN LAST12 = 0;
	IF RECENT6_60 = . THEN RECENT6_60 = 0;
	IF FIRST6_60 = . THEN FIRST6_60 = 0;
	IF LAST12_60 = . THEN LAST12_60 = 0;
	IF RECENT3 = . THEN RECENT3 = 0;
	IF RECENT4TO6 = . THEN RECENT4TO6 = 0;
	DROP CD30;
	FORMAT DELQ1-DELQ15 CDFMT.;
RUN;

PROC SORT 
	DATA = ATB4 NODUPKEY; 
	BY BRACCTNO; 
RUN; /* SORT TO MERGE */

DATA XSDLQ; 
	SET ATB4; 
	DROP NULL; /* DROPPING THE NULL COLUMN (NOT NULLS IN DATASET) */
RUN;

DATA XS;
	SET MERGED_L_B2;
	IF CAMP_TYPE = "XS";
RUN;

PROC SORT 
	DATA = XS; /* SORT TO MERGE */
	BY BRACCTNO;
RUN;

DATA XSWITHDLQ; /* MERGE PULL AND DQL INFORMATION */
	MERGE XS(IN = x) XSDLQ(IN = y);
	BY BRACCTNO;
	IF x = 1;
RUN;

DATA MERGED_L_B2;
	SET FBWITHDLQ XSWITHDLQ;
RUN;

*** APPLY ALL DELINQUENCY RELATED FLAGS -------------------------- ***;
DATA MERGED_L_B2; /* FLAG FOR BAD DLQATB */
	SET MERGED_L_B2;
	*IF TIMES30 = "." THEN TIMES30 = 0;
	IF RECENT3 > 1 OR RECENT6 >2 OR LAST12 > 3 OR LAST12_60 > 1 OR 
	   RECENT6_60 > 0 THEN DLQ_FLAG = "X";
	IF CAMP_TYPE = "XS" & LAST12_60 > 0 THEN DLQ_FLAG = "X";
 	IF TIMES30 = "." AND CAMP_TYPE = "FB" THEN DLQ_FLAG = "X"; 
 /* IF OWNBR = "0537" THEN HARVEY = "BEAUMONT DROP"; */
 /* IF BRNO ="0537" THEN HARVEY="BEAUMONT DROP";*/
RUN;

PROC SORT 
	DATA = MERGED_L_B2 OUT = DEDUPED NODUPKEY;
	BY BRACCTNO;
RUN;

*** EXPORT FLAGGED FILE ------------------------------------------ ***;
PROC EXPORT 
	DATA = DEDUPED OUTFILE = "&FINALEXPORTFLAGGED" DBMS = TAB; 
RUN;

*** CREATE FINAL FILE FOR DROPS ---------------------------------- ***;
DATA FINAL; 
	SET DEDUPED; 
RUN;

DATA WATERFALL;
	LENGTH CRITERIA $50 COUNT 8.;
	INFILE DATAlINES DLM = "," TRUNCOVER;
	INPUT CRITERIA $ COUNT;
	DATAlINES;
	TCI DATA,
	XS TOTAL,
	FB TOTAL,
	XS + FB TOTAL,		
	DELETE CUST IN BAD BRANCHES,	
	DELETE CUST WITH MISSING INFO,	
	DELETE CUST OUTSIDE OF FOORPRINT,	
	DELETE WHERE STATE/OWNST MISMATCH,
	DELETE FB WITH OPEN LOAN,
	DELETE ANY CUSTOMER WITH > 1 LOAN,
	DELETE CUST WITH BAD POCODE,
	DELETE DECEASED,
	DELETE IF LESS THAN TWO PAYMENTS MADE,	
	DELETE FOR ATB DELINQUENCY,	
	DELETE FOR CONPROFILE DELINQUENCY,
	DELETE FOR 5 YR. CONPROFILE DELINQUENCY,
	DELETE FOR BANKRUPTCY (5yr),
	DELETE FOR STATFLAG (5yr),
	DELETE FOR TRW STATUS (5yr),
	DELETE IF DNS OR DNH,
	DELETE CUST WITH NULL DATE OF BIRTH,
	DELETE CUST WITH BAD SSN,
	DELETE NC AUTO UNMADES,	
	DELETE XS BAD FICOS,	
	DELETE DELINQUENT RENEWAL,
	DELETE PLAMT GREATER THAN $0,	
	HEAVY HARVEY EXCLUSIONS (27 BRANCHES),
	DELETE DUPLICATE ADDRESSES,
	;
RUN;

PROC SQL; /* COUNT OBS */ 
	CREATE TABLE COUNT AS SELECT COUNT(*) AS COUNT FROM TCI; 
QUIT;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM XS_TOTAL; 
QUIT;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FB; 
QUIT;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM MERGED_L_B_XS_FB2; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADBRANCH_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF MISSINGINFO_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF OOS_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF STATE_MISMATCH_FLAG = "" OR
	   STATE_MISMATCH_FLAG = "X"; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF OPEN_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF OPEN_FLAG2 = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADPOCODE_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL;
	SET FINAL; 
	IF DECEASED_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF LESSTHAN2_FLAG = ""; 
RUN; 

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF DLQ_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF CONPROFILE_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF CON1YR_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF BK5_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF STATFL_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF TRW_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF DNS_DNH_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF NULLDOB_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADSSN_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF NCAUTOUN_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADFICO_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF DLQREN_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF PLAMT_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF HARVEY = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF DUPADDRESS_FLAG = ""; 
RUN;

PROC SQL; /* COUNT OBS */ 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

PROC PRINT 
	DATA = COUNT NOOBS; /* PRINT FINAL COUNT TABLE */
RUN;

PROC PRINT 
	DATA = WATERFALL; /* PRINT WATERFALL */
RUN;

DATA FINAL;
	LENGTH MONTH_SPLIT $6;
	SET FINAL;
	IF SUBSTR(SSNO1, 9, 1) IN (1, 3, 5, 7, 9) THEN MONTH_SPLIT = "ODD";
	ELSE MONTH_SPLIT = "EVEN";
RUN;

*** EXPORT FINAL FILE -------------------------------------------- ***;
PROC EXPORT 
	DATA = FINAL OUTFILE = "&FINALEXPORTDROPPED" DBMS = TAB REPLACE;
RUN;

*** SEND TO DOD -------------------------------------------------- ***;
DATA MLA;
	SET FINAL;
	KEEP SSNO1 DOB LASTNAME FIRSTNAME MIDDLENAME BRACCTNO SSNO1_A;
	LASTNAME = compress(LASTNAME,"ABCDEFGHIJKLMNOPQRSTUVWXYZ " , "kis");
	MIDDLENAME = compress(MIDDLENAME,"ABCDEFGHIJKLMNOPQRSTUVWXYZ " , "kis");
	FIRSTNAME = compress(FIRSTNAME,"ABCDEFGHIJKLMNOPQRSTUVWXYZ " , "kis");
	SSNO1_A = compress(SSNO1,"1234567890" , "ki");
	SSNO1 = put(input(SSNO1_A,best9.),z9.);
	DOB = compress(DOB,"1234567890 " , "kis");
	if DOB = ' ' then delete;
RUN;

DATA MLA;
	SET MLA;
	IDENTIFIER = "S";
RUN;

PROC DATASETS;
	MODIFY MLA;
	RENAME DOB = "Date of Birth"n 
		   SSNO1 = "Social Security Number (SSN)"n
		   LASTNAME = "Last NAME"n 
		   FIRSTNAME = "First NAME"n 
		   MIDDLENAME = "Middle NAME"n 
		   BRACCTNO = "Customer Record ID"n
		   IDENTIFIER = "Person Identifier CODE"n;
RUN;

DATA FINALMLA;
	LENGTH "Social Security Number (SSN)"n $ 9 
		   "Date of Birth"n $ 8
		   "Last NAME"n $ 26
		   "First NAME"n $20
		   "Middle NAME"n $ 20
		   "Customer Record ID"n $ 28
		   "Person Identifier CODE"n $ 1;
	SET MLA;
RUN;

PROC PRINT 
	DATA = FINALMLA(OBS = 10);
RUN;

PROC CONTENTS
	DATA = FINALMLA;
RUN;

DATA _NULL_;
	SET FINALMLA;
	FILE "\\mktg-app01\E\Production\MLA\MLA-INput files TO WEBSITE\FBCC_20210113.txt";
	PUT @ 1 "Social Security Number (SSN)"n 
		@ 10 "Date of Birth"n 
		@ 18 "Last NAME"n 
		@ 44 "First NAME"n 
		@ 64 "Middle NAME"n 
		@ 84 "Customer Record ID"n
		@ 112 "Person Identifier CODE"n;
RUN;
/*
*** MLA Fake Return -------------------------------------------------- ***;
DATA MLA;
	SET FINAL;
	KEEP SSNO1 DOB LASTNAME FIRSTNAME MIDDLENAME BRACCTNO SSNO1_A;
	LASTNAME = compress(LASTNAME,"ABCDEFGHIJKLMNOPQRSTUVWXYZ " , "kis");
	MIDDLENAME = compress(MIDDLENAME,"ABCDEFGHIJKLMNOPQRSTUVWXYZ " , "kis");
	FIRSTNAME = compress(FIRSTNAME,"ABCDEFGHIJKLMNOPQRSTUVWXYZ " , "kis");
	SSNO1_A = compress(SSNO1,"1234567890" , "ki");
	SSNO1 = put(input(SSNO1_A,best9.),z9.);
	DOB = compress(DOB,"1234567890 " , "kis");
	if DOB = ' ' then delete;
RUN;

DATA MLA;
	SET MLA;
	IDENTIFIER = "S";
	MLA_DOD = "NZ20200212LRSMCSDJV1NWC1C";

RUN;

PROC DATASETS;
	MODIFY MLA;
	RENAME DOB = "Date of Birth"n 
		   SSNO1 = "Social Security Number (SSN)"n
		   LASTNAME = "Last NAME"n 
		   FIRSTNAME = "First NAME"n 
		   MIDDLENAME = "Middle NAME"n 
		   BRACCTNO = "Customer Record ID"n
		   IDENTIFIER = "Person Identifier CODE"n
		   MLA_DOD = "MLA DOD"n;;
RUN;

DATA FINALMLA;
	LENGTH "Social Security Number (SSN)"n $ 9 
		   "Date of Birth"n $ 8
		   "Last NAME"n $ 26
		   "First NAME"n $20
		   "Middle NAME"n $ 20
		   "Customer Record ID"n $ 28
		   "Person Identifier CODE"n $ 1
		   "MLA DOD"n $ 24;
	SET MLA;
RUN;

PROC PRINT 
	DATA = FINALMLA(OBS = 10);
RUN;

PROC CONTENTS
	DATA = FINALMLA;
RUN;

DATA _NULL_;
	SET FINALMLA;
	FILE "\\mktg-app01\E\Production\MLA\MLA-Output files FROM WEBSITE\MLA_5_3_FBCC_20200825.txt";
	PUT @ 1 "Social Security Number (SSN)"n 
		@ 10 "Date of Birth"n 
		@ 18 "Last NAME"n 
		@ 44 "First NAME"n 
		@ 64 "Middle NAME"n 
		@ 84 "Customer Record ID"n
		@ 112 "Person Identifier CODE"n
		@ 122 "MLA DOD"n;
RUN;
*/
*** STEP 2: WHEN FILE IS RETURNED FROM DOD, RUN CODE BELOW         ***;
*** DO NOT CHANGE FILE NAME -------------------------------------- ***;
FILENAME MLA1
"\\mktg-app01\E\Production\MLA\MLA-Output files FROM WEBSITE\MLA_5_6_FBCC_20210113.txt";

DATA MLA1;
	INFILE MLA1;
	INPUT SSNO1 $ 1-9 DOB $ 10-17 LASTNAME $ 18-43 FIRSTNAME $ 44-63
		  MIDDLENAME $ 64-83  BRACCTNO $ 84-111 PI_CODE $ 112-120 
		  MLA_DOD $121-145;
	MLA_STATUS = SUBSTR(MLA_DOD, 1, 1);
RUN;

PROC PRINT 
	DATA = MLA1(OBS = 10);
RUN;

DATA FBCCFINAL; 
	SET FINAL; 
RUN;

PROC SORT 
	DATA = FBCCFINAL; 
	BY BRACCTNO; 
RUN;

PROC SORT 
	DATA = MLA1; 
	BY BRACCTNO; 
RUN;

DATA FINALHH;
	MERGE FBCCFINAL(IN = x) MLA1;
	BY BRACCTNO;
	IF x;
	RENAME CRSCORE = FICO;
RUN;

*** COUNT FOR WATERFALL ------------------------------------------ ***;
PROC FREQ 
	DATA = FINALHH;
	TABLE MLA_STATUS / NOCUM NOPERCENT;
RUN;

DATA FINALHH1;
	LENGTH FICO_RANGE_25PT $10 CAMPAIGN_ID $25 MADE_UNMADE $15
		   CIFNO $20 CUSTID $20 MGC $20 STATE1 $5 TEST_CODE $20;
	SET FINALHH;
	IF MLA_STATUS = "N";
	IF FICO = 0 THEN FICO_RANGE_25PT = "0";
	IF 0 < FICO < 500 THEN FICO_RANGE_25PT = "<500";
	IF 500 <= FICO <= 524 THEN FICO_RANGE_25PT = "500-524";
	IF 525 <= FICO <= 549 THEN FICO_RANGE_25PT = "525-549";
	IF 550 <= FICO <= 574 THEN FICO_RANGE_25PT = "550-574";
	IF 575 <= FICO <= 599 THEN FICO_RANGE_25PT = "575-599";
	IF 600 <= FICO <= 624 THEN FICO_RANGE_25PT = "600-624";
	IF 625 <= FICO <= 649 THEN FICO_RANGE_25PT = "625-649";
	IF 650 <= FICO <= 674 THEN FICO_RANGE_25PT = "650-674";
	IF 675 <= FICO <= 699 THEN FICO_RANGE_25PT = "675-699";
	IF 700 <= FICO <= 724 THEN FICO_RANGE_25PT = "700-724";
	IF 725 <= FICO <= 749 THEN FICO_RANGE_25PT = "725-749";
	IF 750 <= FICO <= 774 THEN FICO_RANGE_25PT = "750-774";
	IF 775 <= FICO <= 799 THEN FICO_RANGE_25PT = "775-799";
	IF 800 <= FICO <= 824 THEN FICO_RANGE_25PT = "800-824";
	IF 825 <= FICO <= 849 THEN FICO_RANGE_25PT = "825-849";
	IF 850 <= FICO <= 874 THEN FICO_RANGE_25PT = "850-874";
	IF 875 <= FICO <= 899 THEN FICO_RANGE_25PT = "875-899";
	IF 975 <= FICO <= 999 THEN FICO_RANGE_25PT = "975-999";
	IF FICO = "" THEN FICO_RANGE_25PT = "";
	IF SOURCE_2 = "RETAIL" THEN CAMPAIGN_ID = "&RETAIL_ID";
	IF SOURCE_2 = "AUTO" THEN CAMPAIGN_ID = "&AUTO_ID";
	IF CAMP_TYPE = "FB" THEN CAMPAIGN_ID = "&FB_ID";
	IF POFFDATE > "&_1MONTH" THEN RECENTPYOUT = "YES";
	ELSE RECENTPYOUT = "NO";
	IF MONTH_SPLIT = "&ODD_EVEN" | RECENTPYOUT = "YES";
	CUSTID = STRIP(_N_);

	IF CAMP_TYPE = "FB" THEN DO;
		IF LNAMT >= 1500 & TIMES30 = 0 THEN RISK_SEGMENT = "A";
		IF LNAMT >= 1500 & FIRST6 > 0 THEN RISK_SEGMENT = "A and B";
		IF LNAMT >= 1500 & FIRST6 = . & TIMES30 NE 0 
			THEN RISK_SEGMENT = "A and B";
		IF LNAMT >= 1500 & TIMES30 NE 0 THEN RISK_SEGMENT = "A and B";
		IF LNAMT < 1500 THEN RISK_SEGMENT = "A and B";
		IF OWNST = "TX" AND 
		   SERCHG = 100 AND 
		   TILA_LNAMT > 1380 AND 
		   MOS_ON_BOOKS < 12 THEN RISK_SEGMENT = "AT";
	END;

RUN;

*** Create suppression filter for texas loans -------------------- ***;
DATA TX_LOAN; /* FROM LOAN TABLE FOR FB */
	SET dw.vw_loan_nlS (
		KEEP = CIFNO LOANDATE OWNST SERCHG TILA_LNAMT);
	WHERE SERCHG = 100 & 
		  TILA_LNAMT > 1380 & 
		  OWNST IN ("TX");
	LOANDATE_SAS = INPUT(STRIP('LOANDATE'n), yymmdd10.);
	FORMAT LOANDATE_SAS yymmdd10.;
	DAYS_ON_BOOKS = TODAY() - LOANDATE_SAS;
	MOS_ON_BOOKS = ROUND(DAYS_ON_BOOKS / 30, 0.01);
	IF MOS_ON_BOOKS > 12 THEN DELETE;
	CIFNO_MATCH = 0;
	CIFNO_MATCH = CIFNO;
	DROP LOANDATE OWNST SERCHG TILA_LNAMT LOANDATE_SAS DAYS_ON_BOOKS 
		 MOS_ON_BOOKS;
RUN;

PROC SORT 
	DATA = FINALHH1; 
	BY CIFNO; 
RUN;

PROC SORT 
	DATA = TX_LOAN NODUPKEY; 
	BY CIFNO; 
RUN;

DATA FINALHH2;
	MERGE FINALHH1(IN = x) TX_LOAN(IN = y);
	BY CIFNO;
	IF x = 1;
	IF CIFNO_MATCH > 0 AND CAMP_TYPE NE "XS" THEN RISK_SEGMENT = "AT";
RUN;

**********************************************************************;
********************************TEST**********************************;
**********************************************************************;

data partial;
	SET DW.VW_PAYMENT(
		keep = TRCD BRACCTNO);
	where TRCD = 'PX';
RUN;

PROC SORT 
	DATA = partial; 
	BY bracctno; 
RUN;

data LOAN;
	SET DW.VW_LOAN(
		keep = CIFNO orgbr poffdate BRACCTNO OWNBR POCD PLCD OWNST);
RUN;

PROC SORT 
	DATA = LOAN; 
	BY BRACCTNO; 
RUN;

DATA SETTLED;
	MERGE PARTIAL(IN = INPART) loan(IN = INLOAN);  
	BY BRACCTNO;  
	IF INPART AND INLOAN;
run;

PROC SORT 
	DATA = FINALHH2; 
	BY BRACCTNO; 
RUN;

DATA FINALHH3;
	MERGE FINALHH2(IN = x) partial(IN = y);
	BY BRACCTNO;
	IF x = 1;
	IF TRCD = 'PX' THEN DELETE;
RUN;

**********************************************************************;
********************************TEST**********************************;
**********************************************************************;

DATA FINALHH2;
	SET FINALHH3;
	RENAME OWNBR = BRANCH
		   FIRSTNAME = CFNAME1
		   MIDDLENAME = CMNAME1
		   LASTNAME = CLNAME1
		   ADR1 = CADDR1 
		   ADR2 = CADDR2
		   CITY = CCITY 
		   STATE = CST 
		   ZIP = CZIP 
		   SSNO1_RT7 = SSN 
		   CD60 = N_60_DPD 
		   CONPROFILE1 = CONPROFILE;
RUN;

PROC IMPORT 
	DATAFILE = 
	"\\mktg-app01\E\Production\Master Files and Instructions\FBXSMOCC_Offers -20210111.xlsx" /*"Change02252020"*/ 
	DBMS = EXCEL OUT = OFFERS REPLACE; 
RUN;

DATA OFFERS;
	SET OFFERS;
	RISK_SEGMENT = STRIP(RISK_SEGMENT);
RUN;

PROC SORT 
	DATA = FINALHH2; 
	BY CST RISK_SEGMENT; 
RUN;

PROC SORT 
	DATA = OFFERS; 
	BY CST RISK_SEGMENT; 
RUN;

DATA FINALHH4;
	MERGE FINALHH2(IN = x) OFFERS;
	BY CST RISK_SEGMENT;
	IF x;
	*IF NetLoanAmount >= 5000 AND ClassTranslation = "Large" 
		THEN CAD_OFFER = 5000;
	*IF NetLoanAmount < 5000 AND ClassTranslation = "Large" 
		THEN CAD_OFFER = 4000;
	*IF ClassTranslation = "Small" 
		THEN CAD_OFFER = 2400;
	*IF ClassTranslation = "Checks" 
		THEN CAD_OFFER = 2400;
	*IF ClassTranslation = "Small" AND OWNST = "GA"
		THEN CAD_OFFER = 1400;
	*IF ClassTranslation = "Checks" AND OWNST = "GA"
		THEN CAD_OFFER = 1400;
	*IF ClassTranslation = "Small" AND OWNST = "OK"
		THEN CAD_OFFER = 1200;
	*IF ClassTranslation = "Checks" AND OWNST = "OK"
		THEN CAD_OFFER = 1200;
	IF STATE_MISMATCH_FLAG = 'X' THEN BRANCH = '';
	FORMAT AMT_GIVEN1 DOllar10.2;
	*FORMAT CAD_OFFER DOllar10.2;
	RENAME APR = PERCENT;
RUN;

/*  The below data set is added to create a new variable FOOTPRNT  on 8/24/2020 from 9.1 Campaign   */

DATA FINALHH4;
SET FINALHH4;
LENGTH FOOTPRNT $4;
FOOTPRNT='INF';
RUN;

*** IF RISK_SEGMENT = "TEST" THEN TEST_CODE = "RATE_TEST"          ***;
*** ELSE TEST_CODE = "Control" ----------------------------------- ***;

PROC Sql;
	CREATE TABLE FINALHH5 aS
	Select CUSTID, BRANCH, CFNAME1,	CMNAME1, CLNAME1, CADDR1, CADDR2,
		   CCITY, CST, CZIP, SSN, AMT_GIVEN1, PERCENT, numpymntS,
		   CAMP_TYPE, ORig_amtid, FICO, DOB, MLA_STATUS, RISK_SEGMENT, 
		   N_60_DPD, CONPROFILE, BRACCTNO, CIFNO, CAMPAIGN_ID, MGC,
		   MONTH_SPLIT, MADE_UNMADE, FICO_RANGE_25PT, STATE1,
		   TEST_CODE, POFFDATE, phoNE, cellphoNE, SUFFIX, FOOTPRNT, 
		   STATE_MISMATCH_FLAG
	FROM FINALHH4;
QUIT;
RUN;

PROC EXPORT 
	DATA = FINALHH5 OUTFILE = "&FINALEXPORTHH"  DBMS = TAB REPLACE;
RUN;

PROC EXPORT 
	DATA = FINALHH5 OUTFILE = "&FINALEXPORTED" DBMS = cSv REPLACE;
RUN;

DATA check;
	SET FINALHH5;
	IF AMT_GIVEN1 = "";
RUN;

PROC FREQ 
	DATA = FINALHH5;
	TABLES RISK_SEGMENT;
RUN;

PROC FREQ 
	DATA = FINALHH5;
	TABLES MONTH_SPLIT;
RUN;
 
/*
DATA NOTEST TEST;
	SET FINALHH2;
	IF CST = "AL" & RISK_SEGMENT = "A" THEN OUTPUT TEST;
	ELSE OUTPUT NOTEST;
RUN;

PROC SurveySelect 
	DATA = TEST OUT = TEST2 OUTALL rate = .5 method = SrS;
RUN;

DATA FINALHH3;
	SET NOTEST TEST2;
	IF Selected = 1 THEN RISK_SEGMENT = "TEST";
	IF Selected = 0 THEN RISK_SEGMENT = "A";
	RISK_SEGMENT = STRIP(RISK_SEGMENT);
RUN;

PROC FREQ 
	DATA = FINALHH3;
	TABLES RISK_SEGMENT;
RUN;

PROC FREQ 
	DATA = FINALHH5;
	TABLES TEST_CODE;
RUN;
*/