**********************************************************************;
*** IMPORT NEW CROSS SELL FILES. --------------------------------- ***;
*** INSTRUCTIONS HERE: R:\Production\MLA\Files for MLA PROCessINg\ ***;
*** XSELL\XSELL TCI DECSION LENDER.txt --------------------------- ***;
*** CHANGE DATES IN THE LINES IMMEDIATELY BELOW ALONG WITH FILE    ***;
*** PATHS. FOR THE FILES PATHS, YOU WILL LIKELY NEED TO CREATE A   ***;
*** NEW FOLDER "CC" IN THE APPROPRIATE MONTH FILE. DO NOT CHANGE   ***;
*** THE ARGUMENT TO THE LEFT OF THE COMMA - ONLY CHANGE WHAT IS TO ***;
*** THE RIGHT OF THE COMMA. ALSO NOTE THE CHANGE TO "Odd" OR "Even"***; 
*** BASED ON WHAT IS NEEDED FOR THE CURRENT PULL. ---------------- ***;
**********************************************************************;

*** ASSIGN MACRO VARIABLES --------------------------------------- ***;
DATA 
	_NULL_;

	CALL SYMPUT ('_1day','2018-04-01'); /* DAY BEFORE PULL */
	CALL SYMPUT ('_1month','2018-03-02'); /* 1 MONTH FROM PULL */
	CALL SYMPUT ('_16month','2016-12-02'); /*16 MONTHS FROM PULL*/
	CALL SYMPUT('_3year','2015-04-02'); /* 3 YEARS FROM PULL */
	CALL SYMPUT('_5year','2013-04-02'); /* 5 YEARS FROM PULL */
	CALL SYMPUT ('_15month','2017-01-02'); /*15 MONTHS FROM PULL*/

	*** ASSIGN ID MACRO VARIABLES -------------------------------- ***;
	CALL SYMPUT ('retail_id', 'RetailXS_5.0_2018');
	CALL SYMPUT ('auTO_id', 'AuTOXS_5.0_2018');
	CALL SYMPUT ('fb_id', 'FB_5.0_2018CC');

	*** ASSIGN ODD/EVEN MACRO VARIABLE --------------------------- ***;
	CALL SYMPUT ('odd_even', 'Odd'); 

	*** ASSIGN DATA FILE MACRO VARIABLE -------------------------- ***;
	CALL SYMPUT ('fINalexportFLAGged', 
		'\\mktg-app01\E\Production\2018\04-April_2018\FBXSCC\FBXS_CC_.20180402FLAGGED_V2.txt');
	CALL SYMPUT ('fINalexportDROPped', 
		'\\mktg-app01\E\Production\2018\04-April_2018\FBXSCC\FBXS_CC_20180402FINAL_V2.txt');
	CALL SYMPUT ('exportMLA', 
		'\\mktg-app01\E\Production\MLA\MLA-INput files TO WEBSITE\FBCC_20180402_V2.txt');
	CALL SYMPUT ('fINalexportED', 
		'\\mktg-app01\E\Production\2018\04-April_2018\FBXSCC\FBXS_CC_20180402FINAL_HH_V2.csv');
	CALL SYMPUT ('fINalexportHH', 
		'\\mktg-app01\E\Production\2018\04-April_2018\FBXSCC\FBXS_CC_20180402FINAL_HH_V2.txt');
RUN;

*** CHECK THAT MACRO VARIABLES WERE ASSIGNED CORRECTLY ----------- ***;
%PUT "&_15monthsago" "&_5yrdate" "&yesterday";

*** NEW TCI DATA - RETAIL AND AUTO ------------------------------- ***;
PROC IMPORT 
	DATAFILE = 
		"\\mktg-app01\E\cepps\FBXS\XS_Mail_Pull.xlsx" 
		DBMS = XLSX OUT = XS REPLACE;
	RANGE = "XS Mail Pull$A3:0";
	GETNAMES = YES;
RUN;

*** FORMAT THE `NEWXS` DATASET AND STORE AS `NEWXS2` ------------- ***;
DATA XS2;
	SET XS;

	*** CREATE `SOURCE` VARIABLE AND ASSIGN `LOAN TYPE = AUTO      ***;
	*** INDIRECT` AS `TCICENTRAL` OR `LOAN TYPE = RETAIL` AS       ***; 
	*** `TCIRETAIL` ---------------------------------------------- ***;
	IF 'loan type'n = "AuTO INdirect" THEN SOURCE = "TCICentral";
	IF 'loan type'n = "Retail" THEN SOURCE = "TCIRetail";
	IF SOURCE NE "";

	*** SEPERATE `applicant address` VARIABLE INTO `ADR1`, `CITY`, ***; 
	*** `STATE`, AND `ZIP` VARIABLES WHEN `applicant address` DOES ***; 
	*** NOT CONTAIN THE STRING "Apt" ----------------------------- ***;
	IF FIND('applicant address'n, "Apt") = 0 THEN DO;
		ADR1 = SCAN('applicant address'n, 1, ",");
		CITY = SCAN('applicant address'n, 2, ",");
		STATE = SCAN('applicant address'n, 3, ",");
		ZIP = SCAN('applicant address'n, 4, ",");
	END;

	*** SEPERATE `applicant address` VARIABLE INTO `ADR1`, `ADR2`, ***;
	*** `CITY`, `STATE`, AND `ZIP` VARIABLES WHEN `applicant       ***;
	*** address` CONTAINS THE STRING "Apt" ----------------------- ***;
	IF FIND('applicant address'n, "Apt") GE 1 THEN DO;
		ADR1 = SCAN('applicant address'n, 1, ",");
		ADR2 = SCAN('applicant address'n, 2, ",");
		CITY = SCAN('applicant address'n, 3, ",");
		STATE = SCAN('applicant address'n, 4, ",");
		ZIP = SCAN('applicant address'n, 5, ",");
	END;

	*** FORMAT `applicant DOB` AS YYMMDD10 AND STORE IN `DOB`      ***;
	*** VARIABLE. ------------------------------------------------ ***;
	DOB = PUT('applicant DOB'n, YYMMDD10.);

	*** FORMAT `application date` AS MMDDYY10 -------------------- ***;
	'application date1'n = PUT('application date'n, MMDDYY10.);

	*** CONCATENATE "TCI" TO `Application Number` AND STORE AS     ***;
	*** `BRACCTNO` VARIABLE -------------------------------------- ***;
	BRACCTNO = CATS("TCI", 'Application Number'n);

	*** SUB-STRING THE LAST 7 DIGITS FROM THE `applicant ssn`      ***;
	*** VARIABLE AND STORE THEM IN `SSNO1_RT7` VARIABLE ---------- ***;
	SSNO1_RT7 = SUBSTRN('applicant ssn'n, MAX(1, 
		LENGTH('applicant ssn'n) - 6), 7);

	*** DROP THE VARIABLES `Application Date`, `Applicant Address`,***;
	*** `Applicant Address ZIP`, `Applicant DOB`, `app. work phoNE`***;
	*** FROM NEWXS2 DATASET -------------------------------------- ***;
	DROP 'Application Date'n 'Applicant Address'n
		'Applicant Address ZIP'n 'Applicant DOB'n 'app. work phoNE'n;

	*** RENAME THE `application date1`, `applicant email`,         ***;
	*** `Applicant Credit Score`, `Applicant FIRST Name`,          ***;
	*** `Applicant LAST Name`, `Applicant SSN`, `Applicant Middle  ***;
	*** Name`, `app. cell phoNE`, AND `app. home phoNE` VARIABLES  ***;
	RENAME 
		'application date1'n = 'application date'n
		'applicant email'n = EMAIL 
		'Applicant Credit Score'n = CRSCORE
		'Applicant FIRST Name'n = FIRSTNAME
		'Applicant LAST Name'n = LASTNAME 
		'Applicant SSN'n = SSNO1
		'Applicant Middle Name'n = MIDDLENAME 
		'app. cell phoNE'n = CELLPHONE 
		'app. home phoNE'n = PHONE;
RUN;

DATA TCI;

	*** SET LENGTH FOR `ADR1`, `CITY`, `STATE`, `ZIP`,             ***;
	*** `MIDDLENAME`, `SOURCE`, AND `BRACCTNO` VARIABLES --------- ***;
	LENGTH 
		ADR1 $40 
		CITY $25 
		STATE $4 
		ZIP $10 
		MIDDLENAME $25 
		SOURCE $11
		BRACCTNO $15;
	SET XS2;
	SSNO1 = STRIP(SSNO1); /* STRIP WHITE SPACE FROM `SSNO1` */
	DOB = COMPRESS(DOB, "-"); /* REMOVE HYPHEN FROM `DOB` */
	FORMAT _CHARACTER_; /* SET CHAR FORMAT TO SAS DEFAULT */
RUN;

*** READ IN DATA FROM `dw.vw_loan_NLS` TABLE. SUBSET FOR RELEVANT  ***;
*** VARIABLES. FILTER TO ISOLATE XS LOANS. STORE AS `XS_L` DATASET ***;
DATA XS_L;
	
	*** SUBSET `dw.vw_loan_NLS` USING RELEVANT VARIABLES --------- ***;
	SET dw.vw_loan_NLS (
		KEEP = OWNST PURCD CIFNO BRACCTNO ID SSNO1 OWNBR SSNO1_RT7 
			SSNO2 LNAMT NETLOANAMOUNT FINCHG LOANTYPE ENTDATE LOANDATE 
			CLASSID CLASSTRANSLATION XNO_TRUEDUEDATE FIRSTPYDATE SRCD 
			POCD POFFDATE PLCD PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER
			CONPROFILE1 DATEPAIDLAST APRATE CRSCORE CURBAL);
	
	*** FILTER DATA. REMOVE NULLS FROM `CIFNO`. FILTER FOR         ***;
	*** `ENTDATE` FROM A YEAR AGO UNTIL MOST RECENT. KEEP ONLY     ***;
	*** NULLS FROM `POCD`. KEEP ONLY NULLS FROM `PLCD`. KEEP ONLY  ***;
    *** NULLS FROM `PLDATE`. KEEP ONLY NULLS FROM `POFFDATE`. KEEP ***;
	*** ONLY NULLS FROM `BNKRPTDATE`. KEEP RELEVANT `CLASSID`S AND ***;
	*** `OWNST`S ------------------------------------------------- ***;
	WHERE CIFNO NE "" & 
		ENTDATE >= "&_15month" & 
		POCD = "" & 
		PLCD = "" & 
		PLDATE = "" & 
		POFFDATE = ""  & 
		BNKRPTDATE = "" & 
		CLASSID IN (10,19,20,31,34) & 
		OWNST IN ("AL", "GA", "NC", "NM", "OK", "SC", "TN", "TX", "VA");
	
	*** CREATE `SS7BRSTATE` VARIABLE ----------------------------- ***;
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2)); 
RUN;

*** READ IN DATA FROM `dw.vw_BORROWER_nls` TABLE. SUBSET FOR       ***;
*** RELEVANT VARIABLES. FILTER TO ISOLATE XS LOANS. STORE AS       ***; 
*** `BORRNLS` DATASET -------------------------------------------- ***;
DATA BORRNLS;

	*** SET LENGTH FOR `FIRSTNAME`, `MIDDLENAME`, `LASTNAME` ----- ***;
	LENGTH FIRSTNAME $20 MIDDLENAME $20 LASTNAME $30;

	*** SUBSET `dw.vw_BORROWER_nls` USING RELEVANT VARIABLES ----- ***;
	SET dw.vw_BORROWER_nls (
		KEEP = RMC_UPDATED PHONE CELLPHONE CIFNO SSNO SSNO_RT7  FNAME 
			LNAME ADR1 ADR2 CITY STATE ZIP BRNO AGE CONFIDENTIAL
			SOLICIT CEASEANDDESIST CREDITSCORE);
	WHERE CIFNO NOT =: "B"; /* REMOVE `CIFNO`S THAT BEGIN WITH "B" */
	
	*** STRIP WHITE SPACE FROM `FNAME`, `LNAME`, `ADR1`, `ADR2`,   ***;
	*** `CITY`, `STATE`, `ZIP` ----------------------------------- ***;
	FNAME = STRIP(FNAME);
	LNAME = STRIP(LNAME);
	ADR1 = STRIP(ADR1);
	ADR2 = STRIP(ADR2);
	CITY = STRIP(CITY);
	STATE = STRIP(STATE);
	ZIP = STRIP(ZIP);
	
	*** FIND ALL INSTANCES OF "JR" IN `FNAME`. REMOVE "JR" FROM    ***;
	*** STRING AND STORE AS `FIRSTNAME`. STORE ALL OCCURENCES OF   ***;
	*** "JR" IN NEW VARIABLE, `SUFFIX` --------------------------- ***;
	IF FIND(FNAME, "JR") GE 1 THEN DO;
		FIRSTNAME = COMPRESS(FNAME, "JR");
		SUFFIX = "JR";
	END;
	
	*** FIND ALL INSTANCES OF "SR" IN `FNAME`. REMOVE "SR" FROM    ***;
	*** STRING AND STORE AS `FIRSTNAME`. STORE ALL OCCURENCES OF   ***;
	*** "SR" IN NEW VARIABLE, `SUFFIX` --------------------------- ***;
	IF FIND(FNAME, "SR") GE 1 THEN DO;
		FIRSTNAME = COMPRESS(FNAME, "SR");
		SUFFIX = "SR";
	END;
	
	*** IF `SUFFIX` IS NULL, TAKE 1ST WORD IN `FNAME` AND STORE AS ***;
	*** `FIRSTNAME`. TAKE 2ND, 3RD, AND 4TH WORDS IN `FNAME` AND   ***;
	*** STORE AS `MIDDLENAME` ------------------------------------ ***;
	IF SUFFIX = "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, 1);
		MIDDLENAME = CATX(" ", SCAN(FNAME, 2, " "), 
			SCAN(FNAME, 3, " "), SCAN(FNAME, 4, " "));
	END;
	NWORDS = COUNTW(FNAME, " "); /* COUNT # OF WORDS IN `FNAME` */
	
	*** IF MORE THAN 2 WORDS IN `FNAME`, TAKE 1ST WORD AND STORE IN***; 
	*** `FIRSTNAME`, AND TAKE SECOND WORD AND ADD TO `MIDDLENAME`  ***;
	IF NWORDS > 2 & SUFFIX NE "" THEN DO;
		FIRSTNAME = SCAN(FNAME, 1, " ");
		MIDDLENAME = SCAN(FNAME, 2, " ");
	END;
	DOB = COMPRESS(AGE, "-"); /* REMOVE HYPHEN, STORE `AGE` AS `DOB` */
	LASTNAME = LNAME; /* STORE `LNAME` AS `LASTNAME` */
	DROP FNAME LNAME NWORDS AGE; /* DROP VARIABLES FROM TABLE */
	IF CIFNO NE ""; /* FILTER SET OF NULL `CIFNO`S */

	*** STORE `SSNO` AS `SSNO1`. *STORE `SSNO_RT7` AS `SSNO1_RT7`  ***;
	SSNO1 = SSNO;
	SSNO1_RT7 = SSNO_RT7;
RUN;

*** SPLIT: GROUP BY `CIFNO` - APPLY: FIND MAX `ENTDATE` PER `CIFNO`***:
*** - COMBINE: STORE RECORDS WITH MAX `ENTDATE` PER `CIFNO` IN     ***;
*** `XS_LDEDUPED` TABLE ------------------------------------------ ***;
PROC SQL;
	CREATE TABLE XS_LDEDUPED AS
	SELECT *
	FROM XS_L
	GROUP BY CIFNO
	HAVING ENTDATE = MAX(ENTDATE);
QUIT;

*** REMOVE RECORDS WITH DUPLICATE `CIFNO` FROM `XS_LDEDUPED` ----- ***;
PROC SORT 
	DATA = XS_LDEDUPED NODUPKEY; 
	BY CIFNO; 
RUN;

*** SORT `BORRNLS` BY `CIFNO` DEFAULT ASCENDING THEN BY            ***;
*** `RMC_UPDATED` DESCENDING ------------------------------------- ***;
PROC SORT 
	DATA = BORRNLS; 
	BY CIFNO DESCENDING RMC_UPDATED; 
RUN;

*** REMOVE RECORDS WITH DUPLICATE `CIFNO` FROM `BORRNLS` --------- ***;
PROC SORT 
	DATA = BORRNLS OUT = BORRNLS2 NODUPKEY; 
	BY CIFNO; 
RUN;

*** MERGE `XS_LDEDUPED` AND `BORRNLS2` BY `CIFNO` AS `LOANNLSXS` - ***;
DATA LOANNLSXS;
	MERGE XS_LDEDUPED(IN = x) BORRNLS2(IN = y);
	BY CIFNO;
	IF x AND y;
RUN;

DATA XS; /* STACK ALL DW XS LOANS */
	SET LOANNLSXS;
RUN;

*** MERGE `XS` FROM OUR DW WITH INFO FROM TCI SITES TO IDENTIFY    ***;
*** MADE APPLICATIONS AND TO ID UNMADE APPLICATIONS -------------- ***;
PROC SORT 
	DATA = XS;
	BY SSNO1_RT7;
RUN;

PROC SORT 
	DATA = TCI;
	BY SSNO1_RT7;
RUN;

DATA TCI2MADES;
	SET TCI;
	DROP BRACCTNO;
RUN;

DATA MADES;
	MERGE XS(IN = x) TCI2MADES(IN = y);
	BY SSNO1_RT7;
	IF x = 1;
RUN;

DATA UNMADES;
	MERGE XS(IN = x) TCI(IN = y);
	BY SSNO1_RT7;
	IF x = 0 AND y = 1;
	MADE_UNMADE = "UNMADE";
RUN;

DATA UNMADES;
	SET UNMADES;
	RENAME 'Date Submitted'n = DATE_SUBMITTED;
	APPLICATION_DATE = INPUT(STRIP('application date'n), mmddyy10.);
	FORMAT APPLICATION_DATE mmddyy10.;
RUN;

DATA UNMADES2;
	SET UNMADES (WHERE = (INTNX('month', TODAY(), -6, 'b') <= 
		APPLICATION_DATE OR APPLICATION_DATE = .));
RUN;

*** FOR MATCHED, KEEP ONLY INFO FROM LOAN AND BORROWER TABLES ---- ***;
DATA MADES2;
	SET MADES;
	MADE_UNMADE = "MADE";
RUN;

*** APPEND MADES AND UNMADES FOR FULL XS UNIVERSE ---------------- ***;
DATA XSTOT; 
	SET UNMADES MADES2;
RUN;

DATA XSTOT;
	SET XSTOT;
	IF SS7BRSTATE = "" THEN SS7BRSTATE = CATS(SSNO1_RT7, 
		SUBSTR(OWNBR, 1, 2));
	IF CRSCORE < 625 THEN RISK_SEGMENT = "624 AND below";
	IF 625 <= CRSCORE < 650 THEN RISK_SEGMENT = "625-649";
	IF 650 <= CRSCORE < 851 THEN RISK_SEGMENT = "650-850";
	IF CLASSID IN (10, 21, 31) THEN SOURCE_2 = "RETAIL";
	IF SOURCE = "TCIRetail" THEN SOURCE_2 = "RETAIL";
	IF CLASSID IN (13, 14, 19, 20, 32, 34, 40, 41, 45, 68, 69, 72, 75,
		78, 79, 80, 88, 89, 90) THEN SOURCE_2 = "AUTO";
	IF SOURCE = "TCICentral" THEN SOURCE_2 = "AUTO";
RUN;

DATA XS_TOTAL;
	LENGTH OFFER_SEGMENT $20;
	SET XSTOT;
	STATE = STRIP(STATE);
	IF CRSCORE = 0 THEN BADFICO_FLAG = "X";
	IF CRSCORE = . THEN BADFICO_FLAG = "X";
	IF CRSCORE > 725 THEN BADFICO_FLAG = "X";
	IF STATE = "NC" & 
	   SOURCE_2 = "AUTO" & 
	   MADE_UNMADE = "UNMADE" 
		THEN NCAUTOUN_FLAG = "X";
	IF STATE = "NC" & 
	   SOURCE_2 = "AUTO" & 
	   MADE_UNMADE = "MADE" 
		THEN OFFER_SEGMENT = "ITA";
	IF STATE IN ("GA", "VA") 
		THEN OFFER_SEGMENT = "ITA";
	IF STATE IN ("SC","TX","TN","AL","OK","NM") & 
	   SOURCE_2 = "AUTO" 
		THEN OFFER_SEGMENT = "ITA";
	IF STATE IN ("SC","NC","TX","TN","AL","OK","NM") & 
	   SOURCE_2 = "RETAIL" & 
	   RISK_SEGMENT = "624 AND below" 
		THEN OFFER_SEGMENT = "ITA";
RUN;

*** DEDUPE XS ---------------------------------------------------- ***;
DATA XS_TOTAL;
	SET XS_TOTAL;
	IF OFFER_SEGMENT NE "ITA"; /* DROP ITA'S */
	CAMP_TYPE = "XS";
RUN;

*** STEP 1: PULL IN DATA FOR `FB`S ------------------------------- ***;
DATA LOAN_PULL; /* FROM LOAN TABLE FOR FB */
	SET dw.vw_loan_nls (
		KEEP = PURCD CIFNO BRACCTNO ID OWNBR OWNST SSNO1_RT7 SSNO1
			   SSNO2 NETLOANAMOUNT LNAMT FINCHG SSNO1_RT7 LOANTYPE
			   ENTDATE LOANDATE CLASSID CLASSTRANSLATION
			   XNO_TRUEDUEDATE FIRSTPYDATE SRCD POCD POFFDATE PLCD
			   PLDATE PLAMT BNKRPTDATE BNKRPTCHAPTER DATEPAIDLAST
			   APRATE CRSCORE CURBAL);
	WHERE POFFDATE BETWEEN "&_15month" AND "&_1day" & 
		  POCD = "13" & 
		  OWNST IN ("AL", "GA", "NC", "NM", "OK", "SC", "TN", "TX",
					"VA"); /* PAID OUT LOANS */
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
RUN;

PROC SQL;
	CREATE TABLE LOAN1NLSFB AS
	SELECT *
	FROM LOAN_PULL
	GROUP BY CIFNO
	HAVING ENTDATE = MAX(ENTDATE);
QUIT;

PROC SORT 
	DATA = LOAN1NLSFB;
	BY CIFNO;
RUN;

DATA LOANNLSFB;
	MERGE LOAN1NLSFB(IN = x) BORRNLS2(IN = y);
	BY CIFNO;
	IF x AND y;
RUN;

DATA FB;
	SET LOANNLSFB;
	CAMP_TYPE = "FB";
RUN;

*** APPEND XS TO FB ---------------------------------------------- ***;
DATA MERGED_L_B_XS_FB;
	SET FB XS_TOTAL;
RUN;

PROC SORT 
	DATA = MERGED_L_B_XS_FB OUT = MERGED_L_B_XS_FB2 NODUPKEY;
	BY BRACCTNO;
RUN;

*** PULL IN INFORMATION FOR STATFLAGS ---------------------------  ***;
DATA STATFLAGS;
	SET dw.vw_loan(KEEP = OWNBR SSNO1_RT7 ENTDATE STATFLAGS);
	WHERE ENTDATE > "&_3year" & 
		  STATFLAGS NE "";
RUN;

PROC SQL; /* IDENTIFYING BAD STATFLAGS */
 	CREATE TABLE STATFLAGS2 AS
	SELECT * 
	FROM STATFLAGS 
	WHERE STATFLAGS CONTAINS "4" OR STATFLAGS CONTAINS "5" OR
		  STATFLAGS CONTAINS "6" OR STATFLAGS CONTAINS "7" OR
		  STATFLAGS CONTAINS "A" OR STATFLAGS CONTAINS "B" OR
		  STATFLAGS CONTAINS "C" OR STATFLAGS CONTAINS "D" OR
		  STATFLAGS CONTAINS "I" OR STATFLAGS CONTAINS "J" OR
		  STATFLAGS CONTAINS "L" OR STATFLAGS CONTAINS "P" OR
		  STATFLAGS CONTAINS "R" OR STATFLAGS CONTAINS "V" OR
		  STATFLAGS CONTAINS "W" OR STATFLAGS CONTAINS "X" OR
		  STATFLAGS CONTAINS "S";
RUN;

*** TAGGING BAD STATFLAGS ---------------------------------------- ***;
DATA STATFLAGS2; 
	SET STATFLAGS2;
	STATFL_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE OWNBR SSNO1_RT7;
	RENAME STATFLAGS = STATFLAGS_OLD;
RUN;

PROC SORT DATA = STATFLAGS2 NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT DATA = MERGED_L_B_XS_FB2;
	BY SS7BRSTATE;
RUN;

*** MERGE FILE WITH STATFLAG FLAGS ------------------------------- ***;
DATA MERGED_L_B2;
	MERGE MERGED_L_B_XS_FB2(IN = x) STATFLAGS2;
	BY SS7BRSTATE;
	IF x = 1;
RUN;

*** FLAG BANKRUPTCIES IN PAST 5 YEARS ---------------------------- ***;
DATA BK5YRDROPS;
	SET dw.vw_loan (
		KEEP = ENTDATE SSNO1_RT7 OWNBR BNKRPTDATE BNKRPTCHAPTER);
	WHERE ENTDATE > "&_5year";
RUN;
DATA BK5YRDROPS;
	SET BK5YRDROPS;
	WHERE BNKRPTCHAPTER > 0 | BNKRPTDATE NE "";
RUN;
DATA BK5YRDROPS;
	SET BK5YRDROPS;
	BK5_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP BNKRPTDATE ENTDATE SSNO1_RT7 OWNBR BNKRPTCHAPTER;
RUN;

PROC SORT 
	DATA = BK5YRDROPS NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) BK5YRDROPS;
	BY SS7BRSTATE;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	IF BNKRPTDATE NE "" THEN BK5_FLAG = "X";
	IF BNKRPTCHAPTER NOT IN (0, .) THEN BK5_FLAG = "X";
RUN;

*** FLAG BAD TRW STATUS ------------------------------------------ ***;
DATA TRWSTATUS_FL; /* FIND FROM 5 YEARS BACK */
	SET dw.vw_loan(KEEP = OWNBR SSNO1_RT7 ENTDATE TRWSTATUS);
	WHERE ENTDATE > "&_5yr" & TRWSTATUS NE "";
RUN;

DATA TRWSTATUS_FL; /* FLAG FOR BAD TRW'S */ 
	SET TRWSTATUS_FL;
	TRW_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE SSNO1_RT7 OWNBR;
RUN;

PROC SORT 
	DATA = TRWSTATUS_FL NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2; /* MERGE PULL WITH TRW FLAGS */
	MERGE MERGED_L_B2(IN = x) TRWSTATUS_FL;
	BY SS7BRSTATE;
	IF x;
RUN;

*** IDENTIFY BAD PO CODES ---------------------------------------- ***;
DATA PO_CODES_3YR;
	SET dw.vw_loan(KEEP = ENTDATE POCD SSNO1_RT7 OWNBR);
	WHERE ENTDATE > "&_3yr" & POCD IN ("49", "50", "61", "62", "63",
									   "64", "66", "68", "93", "97");
RUN;

DATA PO_CODES_3YR;
	SET PO_CODES_3YR;
	BADPOCODE_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE POCD SSNO1_RT7 OWNBR;
RUN;

PROC SORT 
	DATA = PO_CODES_3YR NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) PO_CODES_3YR;
	BY SS7BRSTATE;
	IF x;
RUN;

DATA PO_CODES_FOREVER;
	SET dw.vw_loan(KEEP = ENTDATE POCD SSNO1_RT7 OWNBR);
	WHERE POCD IN ("21", "94", "95", "96");
RUN;

DATA PO_CODES_FOREVER;
	SET PO_CODES_FOREVER;
	DECEASED_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE POCD SSNO1_RT7 OWNBR;
RUN;

PROC SORT 
	DATA=PO_CODES_FOREVER NODUPKEY;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) PO_CODES_FOREVER;
	BY SS7BRSTATE;
	IF x;
RUN;


DATA CON1YR_FL; /* FIND FROM 2 YEARS BACK */
	SET dw.vw_loan(KEEP = OWNBR SSNO1_RT7 ENTDATE CONPROFILE1);
	WHERE ENTDATE > "&_15month" & CONPROFILE1 NE "";
	DATA CON1YR_FL; /* FLAG FOR CON5 */
	SET CON1YR_FL;
	_60 = COUNTC(CONPROFILE1, "2");
	_90 = COUNTC(CONPROFILE1, "3");
	_120A = COUNTC(CONPROFILE1, "4");
	_120B = COUNTC(CONPROFILE1, "5");
	_120C = COUNTC(CONPROFILE1, "6");
	_120D = COUNTC(CONPROFILE1, "7");
	_120E = COUNTC(CONPROFILE1,"8");
	_90PLUS = SUM(_90, _120A, _120B, _120C, _120D, _120E);
	IF _60 > 1 | _90PLUS > 0 THEN CON1YR_FLAG = "X";
	SS7BRSTATE = CATS(SSNO1_RT7, SUBSTR(OWNBR, 1, 2));
	DROP ENTDATE SSNO1_RT7 OWNBR CONPROFILE1;
RUN;

DATA CON1YR_FL_2;
	SET CON1YR_FL;
	IF CON1YR_FLAG = "X";
RUN;

PROC SORT 
	DATA = CON1YR_FL_2 NODUPKEY;
	BY SS7BRSTATE;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SS7BRSTATE;
RUN;

DATA MERGED_L_B2; /* MERGE PULL WITH CON5 FLAGS */
	MERGE MERGED_L_B2(IN = x) CON1YR_FL_2;
	BY SS7BRSTATE;
	IF x;
RUN;

*** IdentIFy IF cusTOmer currently has an open loan for FB ------- ***;
DATA OPENLOANS;
	SET dw.vw_loan(
		KEEP = SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "";
RUN;

DATA SSNO2S;
	SET OPENLOANS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS1;
	SET OPENLOANS SSNO2S;
RUN;

DATA OPENLOANS1;
	SET OPENLOANS1;
	OPEN_FLAG = "X";
	DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;

PROC SORT 
	DATA = OPENLOANS1 NODUPKEY;
	BY SSNO1_RT7;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SSNO1_RT7;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) OPENLOANS1;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	IF CAMP_TYPE = "XS" THEN OPEN_FLAG = "";
RUN;

*** IDENTIFY IF CUSTOMER CURRENTLY HAS AN OPEN LOAN FOR XS UNMADE  ***;
DATA OPENLOANSXS;
	SET dw.vw_loan(
		KEEP = SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "";
RUN;

DATA SSNO2S2;
	SET OPENLOANSXS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS1XS;
	SET OPENLOANSXS SSNO2S2;
RUN;

DATA OPENLOANS1XS;
	SET OPENLOANS1XS;
	OPEN_FLAG = "X";
	DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;
PROC SORT 
	DATA = OPENLOANS1XS NODUPKEY;
	BY SSNO1_RT7;
RUN;

DATA UNMADESDROP MERGED_L_B3;
	SET MERGED_L_B2;
	IF MADE_UNMADE = "UNMADE" THEN OUTPUT UNMADESDROP;
	ELSE OUTPUT MERGED_L_B3;
RUN;

PROC SORT 
	DATA = UNMADESDROP;
	BY SSNO1_RT7;
RUN;

DATA UNMADESDROP;
	MERGE UNMADESDROP(IN = x) OPENLOANS1XS;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B3 UNMADESDROP;
RUN;

DATA OPENLOANS2;
	SET dw.vw_loan(
		KEEP = OWNBR SSNO2 SSNO1_RT7 POCD PLCD POFFDATE PLDATE
			   BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "";
RUN;

DATA SSNO2S;
	SET OPENLOANSXS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS3;
	SET OPENLOANS2 SSNO2S;
RUN;

DATA OPENLOANS4;
	SET OPENLOANS3;
	OPEN_FLAG2 = "X";
	DROP POCD SSNO2 OWNBR PLCD POFFDATE PLDATE BNKRPTDATE;
RUN;

PROC SORT 
	DATA = OPENLOANS4;
	BY SSNO1_RT7;
RUN;

DATA ONE_OPEN MULT_OPEN;
	SET OPENLOANS4;
	BY SSNO1_RT7;
	IF FIRST.SSNO1_RT7 AND LAST.SSNO1_RT7 THEN OUTPUT ONE_OPEN;
	ELSE OUTPUT MULT_OPEN;
RUN;

PROC SORT 
	DATA = MULT_OPEN NODUPKEY;
	BY SSNO1_RT7;
RUN;

PROC SORT 
	DATA = MERGED_L_B2;
	BY SSNO1_RT7;
RUN;

DATA MERGED_L_B2;
	MERGE MERGED_L_B2(IN = x) MULT_OPEN;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA OPENLOANSXS2;
	SET dw.vw_loan(
		KEEP = CLASSTRANSLATION SSNO2 SSNO1_RT7 POCD PLCD POFFDATE
			   PLDATE BNKRPTDATE);
	WHERE POCD = "" & 
		  PLCD = "" & 
		  POFFDATE = "" & 
		  PLDATE = "" & 
		  BNKRPTDATE = "" & 
		  CLASSTRANSLATION NOT IN ("Retail", "AuTO-I", "AuTO-D");
RUN;

DATA SSNO2S2;
	SET OPENLOANSXS;
	IF SSNO2 NE "";
	SSNO1_RT7 = SUBSTR(SSNO2, MAX(1, LENGTH(SSNO2) - 6));
RUN;

DATA OPENLOANS1XS;
	SET OPENLOANSXS2 SSNO2S2;
RUN;

DATA OPENLOANS1XS2;
	SET OPENLOANS1XS;
	OPEN_FLAG3 = "X";
	DROP POCD PLCD POFFDATE PLDATE BNKRPTDATE SSNO2;
RUN;

PROC SORT 
	DATA=OPENLOANS1XS2 NODUPKEY;
	BY SSNO1_RT7;
RUN;

DATA XSPERSONALDROP MERGED_L_B4;
	SET MERGED_L_B2;
	IF CAMP_TYPE = "XS" THEN OUTPUT XSPERSONALDROP;
	ELSE OUTPUT MERGED_L_B4;
RUN;

PROC SORT 
	DATA = XSPERSONALDROP;
	BY SSNO1_RT7;
RUN;

DATA XSPERSONALDROP;
	MERGE XSPERSONALDROP(IN = x) OPENLOANS1XS2;
	BY SSNO1_RT7;
	IF x;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B4 XSPERSONALDROP;
RUN;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	IF OPEN_FLAG3 = "X" THEN OPEN_FLAG2 = "X";
RUN;

*** FLAG NULL DOB                                                  ***;
*** FIND STATES OUTSIDE OF FOORPRINT                               ***;
*** FLAG DNS DNH                                                   ***;
*** FLAG NONMATCHING BRANCH STATE AND BORROWER STATE               ***;
*** FLAG BAD SSNS                                                  ***;
*** FLAG INCOMPLETE INFO                                           ***;
*** FLAG BAD BRANCHES -------------------------------------------- ***;

DATA MERGED_L_B2;
	SET MERGED_L_B2;
	ADR1 = STRIP(ADR1);
	ADR2 = STRIP(ADR2);
	CITY = STRIP(CITY);
	STATE = STRIP(STATE);
	ZIP = STRIP(ZIP);
	CONFIDENTIAL = STRIP(CONFIDENTIAL);
	SOLICIT = STRIP(SOLICIT);
	FIRSTNAME = COMPRESS(FIRSTNAME, '1234567890!@#$^&*()''"%');
	LASTNAME = COMPRESS(LASTNAME, '1234567890!@#$^&*()''"%');
	IF INDEX(FIRSTNAME, """") > 0 THEN NAME_DELETEFLAG = "X";
	IF INDEX(LASTNAME, """") > 0 THEN NAME_DELETEFLAG = "X";
	IF INDEX(FIRSTNAME, "''") > 0 THEN NAME_DELETEFLAG = "X";
	IF INDEX(LASTNAME, "''") > 0 THEN NAME_DELETEFLAG = "X";
	IF ADR1 = "" THEN ADR1 = ADR2;

	*** FLAG INCOMPLETE INFO ------------------------------------- ***;
	IF ADR1 = "" THEN MISSINGINFO_FLAG = "X"; 
	IF STATE = "" THEN MISSINGINFO_FLAG = "X"; 
	IF FIRSTNAME = "" THEN MISSINGINFO_FLAG = "X";   
	IF LASTNAME = "" THEN MISSINGINFO_FLAG = "X";

	*** FLAG INCOMPLETE DOB -------------------------------------- ***;
	IF DOB = "" THEN NULLDOB_FLAG = "X";
	IF OWNBR IN ("600" , "9000" , "198" , "1",
				 "0001" , "0198" , "0600") THEN BADBRANCH_FLAG="X";
	IF SUBSTR(OWNBR, 3, 2) = "99" THEN BADBRANCH_FLAG = "X";
	
	*** FIND STATES OUTSIDE OF FOORPRINT ------------------------- ***;
	IF STATE NOT IN ("AL", "GA", "NC", "NM", "OK",
					 "SC", "TN", "TX", "VA") THEN OOS_FLAG = "X";
	
	*** FLAG CONFIDENTIAL ---------------------------------------- ***;
	IF CONFIDENTIAL = "Y" THEN DNS_DNH_FLAG = "X"; 
	IF SOLICIT = "N" THEN DNS_DNH_FLAG = "X"; /* FLAG DNS */
	IF CEASEANDDESIST = "Y" THEN DNS_DNH_FLAG = "X"; /* FLAG CANDD */
	IF SSNO1 = "" THEN SSNO1 = SSNO;
	IF SSNO1 =: "99" THEN BADSSN_FLAG = "X"; /* FLAG BAD SSNS */
	IF SSNO1 =: "98" THEN BADSSN_FLAG = "X"; /* FLAG BAD SSNS */
	CON_RECENT3 = SUBSTR(CONPROFILE1, 1, 3);
	CON_RECENT4TO6 = SUBSTR(CONPROFILE1, 4, 3);
	CON_RECENT6 = SUBSTR(CONPROFILE1, 1, 6);
	_30_RECENT3 = COUNTC(CON_RECENT3, "1");
	_30_RECENT4TO6 = COUNTC(CON_RECENT4TO6, "1");
	_30_RECENT6 = COUNTC(CON_RECENT6, "1");
	_60_RECENT6 = COUNTC(CON_RECENT6, "2");
	_30 = COUNTC(CONPROFILE1, "1");
	_60 = COUNTC(CONPROFILE1, "2");
	_90 = COUNTC(CONPROFILE1, "3");
	_120A = COUNTC(CONPROFILE1, "4");
	_120B = COUNTC(CONPROFILE1, "5");
	_120C = COUNTC(CONPROFILE1, "6");
	_120D = COUNTC(CONPROFILE1, "7");
	_120E = COUNTC(CONPROFILE1, "8");
	_90PLUS = SUM(_90, _120A, _120B, _120C, _120D, _120E);
	IF _30 > 3 | _60 > 1 | _90PLUS > 0 | _60_RECENT6 > 0 | 
	   _30_RECENT3 > 1 | _30_RECENT6 > 2 
		THEN CONPROFILE_FLAG = "X";
	_9s = COUNTC(CONPROFILE1, "9");
	IF _9s > 10 THEN LESSTHAN2_FLAG = "X";
	XNO_TRUEDUEDATE2 = INput(SUBSTR(XNO_TrueDueDate,6,2)||'/'||SUBSTR(XNO_TrueDueDate,9,2)||'/'||SUBSTR(XNO_TrueDueDate,1,4),mmddyy10.);
FIRSTPyDate2=INput(SUBSTR(FIRSTPyDate,6,2)||'/'||SUBSTR(FIRSTPyDate,9,2)||'/'||SUBSTR(FIRSTPyDate,1,4),mmddyy10.);
Pmt_days=XNO_TRUEDUEDATE2-FIRSTPyDate2;
IF pmt_days<60 THEN LESSTHAN2_FLAG="X";
IF pmt_days = . & _9s <10 THEN LESSTHAN2_FLAG="";
IF pmt_days>=60 & _9s >=10 THEN LESSTHAN2_FLAG="";
IF PlAmt>0 THEN PlAmt_FLAG="X";
IF CAMP_TYPE="FB" THEN do;
IF ownst NE STATE THEN STATE_Mismatch_FLAG = "X"; *FLAG NONMATCHING BRANCH STATE AND BORROWER STATE;
LESSTHAN2_FLAG=""; *Make sure FB FLAG is SET TO NULL;
end;
IF purcd IN ("011","020") THEN dlqren_FLAG="X";
IF brno = "0251" THEN brno="0580";
IF brno = "0252" THEN brno="0683";
IF brno = "0253" THEN brno="0581";
IF brno = "0254" THEN brno="0582";
IF brno = "0255" THEN brno="0583";
IF brno = "0256" THEN brno="1103";
IF brno = "0302" THEN brno="0133";
/*IF brno = "1019" THEN brno="1004";*/
IF brno = "1016" THEN brno="1008";
IF brno = "0877" THEN brno="0806";
IF brno = "0159" THEN brno="0132";
IF brno = "0152" THEN brno="0115";
IF brno = "0885" THEN brno="0802";
IF ZIP=:"29659" & brno="0152" THEN brno="0121";
IF ZIP=:"36264" & brno="0877" THEN brno="0870";
IF brno = "1003" AND ZIP=:"87112" THEN brno="1013";
IF brno = "0872" THEN brno="0807";
IF brno = "0102" THEN brno="0303";
RUN;




*pull AND MERGE dlq INFO for fb's;
PROC format;
   value cdfmt
   1 = 'Current'
   2 = '1-29cd'
   3 = '30-59cd'
   4 = '60-89cd'
   5 = '90-119cd'
   6 = '120-149cd'
   7 = '150-179cd'
   8 = '180+cd'
   other=' ';
RUN;
DATA temp;   
   SET dw.vw_loan(KEEP=bracctno srcd ENTDATE POFFDATE POCD CLASSTRANSLATION lnamt CONPROFILE1 
                       brtrffg SSNO1_RT7 WHERE=(POCD='13' AND POFFDATE > "&_15month"));
   entdt = INput(SUBSTR(ENTDATE,6,2)||'/'||SUBSTR(ENTDATE,9,2)||'/'||SUBSTR(ENTDATE,1,4),mmddyy10.);
   podt = INput(SUBSTR(POFFDATE,6,2)||'/'||SUBSTR(POFFDATE,9,2)||'/'||SUBSTR(POFFDATE,1,4),mmddyy10.);
   IF POFFDATE > "&_1day" THEN delete; 													
   IF put(entdt,yymmn6.) = put(podt,yymmn6.) THEN delete;    
   DROP POFFDATE ENTDATE POCD srcd;
RUN; 
PROC SORT NODUPKEY; BY bracctno; RUN;
DATA atb;
   SET dw.atb_DATA(KEEP=bracctno age2 yearmonth);    
   poacctno = bracctno*1;   
   atbdt = INput(SUBSTR(yearmonth,6,2)||'/'||SUBSTR(yearmonth,9,2)||'/'||SUBSTR(yearmonth,1,4),mmddyy10.);   
   IF age2 =: '1' THEN age2 = '1.Current';   
   KEEP atbdt age2 bracctno;
RUN;
PROC SORT NODUPKEY; BY bracctno atbdt; RUN;
DATA temp;     
   MERGE temp(IN=a) atb(IN=b);
   BY bracctno;
   IF a;  
   cd = SUBSTR(age2,1,1)*1;   
   age = INtck('month',atbdt,podt); 
   IF      age = 1 THEN delq1 = cd;
   ELSE IF age = 2 THEN delq2 = cd;
   ELSE IF age = 3 THEN delq3 = cd;
   ELSE IF age = 4 THEN delq4 = cd;
   ELSE IF age = 5 THEN delq5 = cd;
   ELSE IF age = 6 THEN delq6 = cd;
   ELSE IF age = 7 THEN delq7 = cd;
   ELSE IF age = 8 THEN delq8 = cd;
   ELSE IF age = 9 THEN delq9 = cd;
   ELSE IF age =10 THEN delq10= cd;
   ELSE IF age =11 THEN delq11= cd;
   ELSE IF age =12 THEN delq12= cd;
   ELSE delete;
    IF cd>3 THEN cd60 = 1; *IF cd is greater than 30-59 days late, SET cd60 TO 1;
   IF cd>2 THEN cd30 = 1; *IF cd is greater than 1-29 days late, SET cd30 TO 1;
      IF age<4 THEN do;
		IF cd>2 THEN RECENT3=1; *NOTe 30-59s IN LAST six months;
		end;
		ELSE IF 3<age<7 THEN do;
		IF cd>2 THEN RECENT4TO6=1; *NOTe 30-59s from 7 TO 12 months ago;
		end;
   IF age<7 THEN do;
		IF cd>2 THEN RECENT6=1; *NOTe 30-59s IN LAST six months;
		IF cd>3 THEN RECENT6_60=1;
		end;
		ELSE IF 6<age<13 THEN do;
		IF cd>2 THEN FIRST6=1; *NOTe 30-59s from 7 TO 12 months ago;
		IF cd>3 THEN FIRST6_60=1;
		end;
		KEEP CLASSTRANSLATION bracctno delq1-delq12 cd cd30 cd60 age2 atbdt age RECENT3 RECENT4TO6 RECENT6_60 FIRST6_60 FIRST6 RECENT6;
RUN;
DATA temp2;
SET temp;
LAST12=SUM(RECENT6,FIRST6); *count the number OF 30-59s IN the LAST year when fb had open loan;
LAST12_60=SUM(RECENT6_60,FIRST6_60);
RUN;
PROC SUMmary DATA=temp2 nway missINg;
   class CLASSTRANSLATION bracctno;
   var delq1-delq12 RECENT6 LAST12 FIRST6 RECENT6_60 LAST12_60 FIRST6_60 RECENT3 RECENT4TO6 cd60 cd30;
   OUTPUT out=fINalfb(DROP=_type_ _freq_) SUM=;
RUN; 
DATA fbdlq;
   SET fINalfb;
   times30 = cd30;
   IF times30 = . THEN times30 = 0;
   IF RECENT6 = . THEN RECENT6=0;
   IF FIRST6 = . THEN FIRST6=0;
   IF LAST12 = . THEN LAST12=0;
   IF RECENT6_60= . THEN RECENT6_60=0;
   IF FIRST6_60 = . THEN FIRST6_60=0;
   IF LAST12_60 = . THEN LAST12_60=0;
   IF RECENT3 = . THEN RECENT3 = 0;
   IF RECENT4TO6=. THEN RECENT4TO6=0;
   DROP cd30;
   format delq1-delq12 cdfmt.;
RUN;

PROC SORT DATA=fbdlq NODUPKEY;
 BY BrAcctNo;
 RUN;
 DATA fb;
 SET MERGED_L_B2;
 IF CAMP_TYPE="FB";
 RUN;
PROC SORT DATA=fb; *SORT TO MERGE;
BY BrAcctNo;
RUN;
DATA fbwithdlq; *MERGE pull AND dql INFOrmation;
MERGE fb(IN=x) fbdlq(IN=y);
BY bracctno;
IF x=1;
RUN;



*****************************************;


*Step 14:  pull AND MERGE dlq INFO for xs's;
DATA atb; 
   SET dw.atb_DATA(KEEP=bracctno age2 yearmonth WHERE=(yearmonth between "&_16month" AND "&_1day"));   
   atbdt = INput(SUBSTR(yearmonth,6,2)||'/'||SUBSTR(yearmonth,9,2)||'/'||SUBSTR(yearmonth,1,4),mmddyy10.);     
   age = INtck('month',atbdt,"&sysdate"d);
cd = SUBSTR(age2,1,1)*1;   
 *i.e. for age=1: this is most RECENT month. Fill delq1, which is delq for month 1, with delq status (cd);
   IF      age = 1 THEN delq1 = cd;
   ELSE IF age = 2 THEN delq2 = cd;
   ELSE IF age = 3 THEN delq3 = cd;
   ELSE IF age = 4 THEN delq4 = cd;
   ELSE IF age = 5 THEN delq5 = cd;
   ELSE IF age = 6 THEN delq6 = cd;
   ELSE IF age = 7 THEN delq7 = cd;
   ELSE IF age = 8 THEN delq8 = cd;
   ELSE IF age = 9 THEN delq9 = cd;
   ELSE IF age =10 THEN delq10= cd;
   ELSE IF age =11 THEN delq11= cd;
   ELSE IF age =12 THEN delq12= cd;
   IF cd>3 THEN cd60 = 1; *IF cd is greater than 30-59 days late, SET cd60 TO 1;
   IF cd>2 THEN cd30 = 1; *IF cd is greater than 1-29 days late, SET cd30 TO 1;
      IF age<4 THEN do;
		IF cd>2 THEN RECENT3=1; *NOTe 30-59s IN LAST six months;
		end;
		ELSE IF 3<age<7 THEN do;
		IF cd>2 THEN RECENT4TO6=1; *NOTe 30-59s from 7 TO 12 months ago;
		end;
   IF age<7 THEN do;
		IF cd>2 THEN RECENT6=1; *NOTe 30-59s IN LAST six months;
		IF cd>3 THEN RECENT6_60=1;
		end;
		ELSE IF 6<age<13 THEN do;
		IF cd>2 THEN FIRST6=1; *NOTe 30-59s from 7 TO 12 months ago;
		IF cd>3 THEN FIRST6_60=1;
		end;
		KEEP bracctno delq1-delq12 cd cd30 cd60 age2 atbdt age RECENT3 RECENT4TO6 RECENT6_60 FIRST6_60 FIRST6 RECENT6;
RUN;
DATA atb2;
SET atb;
LAST12=SUM(RECENT6,FIRST6); *count the number OF 30-59s IN the LAST year;
LAST12_60=SUM(RECENT6_60,FIRST6_60);
RUN;
*count cd30, cd60,RECENT6,FIRST6 BY bracctno (*recall loan potentially counted for each month);
PROC SUMmary DATA=atb2 nway missINg;
   class bracctno;
   var delq1-delq12 RECENT6 LAST12 FIRST6 RECENT6_60 LAST12_60 FIRST6_60 RECENT3 RECENT4TO6 cd60 cd30;
   OUTPUT out=fINalxs(DROP=_type_ _freq_) SUM=;
RUN; 
DATA atb4; *create NEw counter variables;
   SET fINalxs;
   times30 = cd30;
   IF times30 = . THEN times30 = 0;
   IF RECENT6 = . THEN RECENT6=0;
   IF FIRST6 = . THEN FIRST6=0;
   IF LAST12 = . THEN LAST12=0;
   IF RECENT6_60= . THEN RECENT6_60=0;
   IF FIRST6_60 = . THEN FIRST6_60=0;
   IF LAST12_60 = . THEN LAST12_60=0;
   IF RECENT3 = . THEN RECENT3 = 0;
   IF RECENT4TO6=. THEN RECENT4TO6=0;
   DROP cd30;
   format delq1-delq12 cdfmt.;
RUN;
PROC SORT DATA=atb4 NODUPKEY; BY bracctno; RUN; *SORT TO MERGE;
DATA xsdlq; SET atb4; DROP NULL; *DROPpINg the NULL column (NOT NULLs IN DATASET); RUN;

DATA xs;
SET MERGED_L_B2;
IF CAMP_TYPE="XS";
RUN;
PROC SORT DATA=xs; *SORT TO MERGE;
BY BrAcctNo;
RUN;
DATA xswithdlq; *MERGE pull AND dql INFOrmation;
MERGE xs(IN=x) xsdlq(IN=y);
BY bracctno;
IF x=1;
RUN;

DATA MERGED_L_B2;
SET fbwithdlq xswithdlq;
RUN;



*Apply all delINquency related FLAGs;
DATA MERGED_L_B2; *FLAG for BAD dlqatb;
SET MERGED_L_B2;
IF RECENT3>1 or RECENT6>2 or LAST12 > 3 or LAST12_60 > 1 or RECENT6_60 >0 THEN DLQ_FLAG="X";
IF CAMP_TYPE="XS" & LAST12_60>0 THEN dlq_FLAG="X";
/*IF OWNBR ="0537" THEN Harvey="Beaumont DROP";*/
/*IF brno ="0537" THEN Harvey="Beaumont DROP";*/
RUN;

PROC SORT DATA=MERGED_L_B2 out= deduped NODUPKEY;
BY BrAcctNo;
RUN;

*Export FLAGged File;
PROC export DATA=deduped outfile="&fINalexportFLAGged" dbms=tab; 
RUN;


 *Create fINal file for DROPs;
 DATA fINal; SET deduped; RUN;


 DATA Waterfall;
 LENGTH Criteria $50 Count 8.;
 INfile DATAlINEs dlm="," tRUNcover;
 INput Criteria $ Count;
 DATAlINEs;
TCI DATA,
XS TOtal,
FB TOtal,
XS + FB TOtal,		
Delete cust IN BAD BRANCHES,	
Delete cust with MissINg INFO,	
Delete cust OUTSIDE OF FOORPRINT,	
Delete WHERE STATE/OwnSt Mismatch,
Delete FB With Open Loan,
Delete Any CusTOmer with >1 Loan,
Delete cust with BAD POCODE,
Delete Deceased,
Delete IF Less than Two Payments Made,	
Delete for ATB DelINquency,	
Delete for ConprOFile DelINquency,
Delete for 5 Yr. ConprOFile DelINquency,
Delete for Bankruptcy (5yr),
Delete for StatFLAG (5yr),
Delete for TRW Status (5yr),
Delete IF DNS or DNH,
Delete cust with NULL Date OF Birth,
Delete cust with BAD SSN,
Delete NC AuTO Unmades,	
Delete XS BAD FICOs,	
Delete DelINquent ReNEwal,
Delete PLAmt greater than $0,	
Heavy Harvey exclusions (27 BRANCHES),	
;
RUN;

PROC SQL; *COUNT OBS; 
	CREATE TABLE COUNT AS SELECT COUNT(*) AS COUNT FROM TCI; 
QUIT;

PROC SQL; *COUNT OBS; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM XS_TOTAL; 
QUIT;

PROC SQL; *COUNT OBS; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FB; quit;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM MERGED_L_B_XS_FB2; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADBRANCH_FLAG = ""; RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF MISSINGINFO_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF OOS_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF STATE_MISMATCH_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF OPEN_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF OPEN_FLAG2 = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADPOCODE_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL;
	SET FINAL; 
	IF DECEASED_FLAG = ""; 
RUN;

PROC SQL; *Count obs;
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF LESSTHAN2_FLAG = ""; 
RUN; 

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF DLQ_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF CONPROFILE_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF CON1YR_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF BK5_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF STATFL_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF TRW_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF DNS_DNH_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT; 

DATA FINAL; 
	SET FINAL; 
	IF NULLDOB_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADSSN_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF NCAUTOUN_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF BADFICO_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF DLQREN_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF PlAmt_FLAG = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

DATA FINAL; 
	SET FINAL; 
	IF HARVEY = ""; 
RUN;

PROC SQL; *Count obs; 
	INSERT INTO COUNT SELECT COUNT(*) AS COUNT FROM FINAL; 
QUIT;

PROC prINt DATA=count noobs;  *PrINt FINal Count Table;
RUN;
PROC prINt DATA=waterfall;  *PrINt Waterfall;
RUN;


DATA fINal;
LENGTH month_split $6;
SET fINal;
IF SUBSTR(SSNO1,9,1) IN (1,3,5,7,9) THEN month_split="Odd";
ELSE month_split="Even";
RUN;


*Export FINal File;
PROC export DATA=fINal outfile="&fINalexportDROPped" dbms=tab replace; RUN;


*Send TO DOD;
DATA mla;
SET fINal;
KEEP SSNO1 DOB LASTNAME FIRSTNAME middlename bracctno;
RUN;

DATA MLA;
	SET MLA;
	IDENTIFIER = "S";
RUN;

PROC DATASETs;
modIFy mla;
rename DOB ="Date OF Birth"n 
	   SSNO1="Social Security Number (SSN)"n 
	   LASTNAME="LAST Name"n 
	   FIRSTNAME="FIRST Name"n 
	   middlename="Middle Name"n 
	   bracctno="CusTOmer Record ID"n
	   IDENTIFIER = "Person IdentIFier Code"n;
RUN;
DATA fINalmla;
LENGTH "Social Security Number (SSN)"n $ 9 
	   "Date OF Birth"n $ 8 
	   "LAST Name"n $ 26 
	   "FIRST Name"n $20 
	   "Middle Name"n $ 20  
	   "CusTOmer Record ID"n $ 28
	   "Person IdentIFier Code"n $ 1;
SET mla;
RUN;

PROC prINt DATA=fINalmla (obs=10); RUN;
PROC contents DATA=fINalmla; RUN;



DATA _NULL_;
 SET fINalmla;
 file "&exportMLA";
 put @1 "Social Security Number (SSN)"n 
	 @10 "Date OF Birth"n 
	 @ 18 "LAST Name"n 
	 @ 44 "FIRST Name"n 
	 @ 64 "Middle Name"n 
	 @ 84 "CusTOmer Record ID"n
	 @ 112 "Person IdentIFier Code"n;
 RUN;




*Step 2: When file is returNEd from DOD, RUN code below;
filename mla1 "\\mktg-app01\E\Production\MLA\MLA-OUTPUT files FROM WEBSITE\MLA_4_4_FBCC_20180402_V2.txt";  *do NOT change file name;
DATA mla1;
INfile mla1;
INput SSNO1 $ 1-9 DOB $ 10-17 LASTNAME $ 18-43 FIRSTNAME $ 44-63 middlename $ 64-83  bracctno $ 84-120 mla_dod $121-145;
mla_status=SUBSTR(mla_dod,1,1);
RUN;
PROC prINt DATA=mla1 (obs=10);
RUN;


DATA fbccfINal; SET fINal; RUN;

PROC SORT DATA=fbccfINal; BY BrAcctNo; RUN;
PROC SORT DATA=mla1; BY BrAcctNo; RUN;

DATA fINalhh;
MERGE fbccfINal(IN=x) mla1;
BY bracctno;
IF x;
rename crscore=fico;
RUN;

*Count for Waterfall;
PROC freq DATA=fINalhh;
table mla_status/nocum nopercent;
RUN;


DATA fINalhh2;
LENGTH fico_range_25pt $10 campaign_id $25 MADE_UNMADE $15 cIFno $20 custid $20 mgc $20 STATE1 $5 test_code $20;
SET fINalhh;
IF mla_status="N";
IF fico=0 THEN fico_range_25pt= "0";
IF 0<fico<500 THEN fico_range_25pt="<500";
IF 500<=fico<=524 THEN fico_range_25pt= "500-524";
IF 525<=fico<=549 THEN fico_range_25pt= "525-549";
IF 550<=fico<=574 THEN fico_range_25pt= "550-574";
IF 575<=fico<=599 THEN fico_range_25pt= "575-599";
IF 600<=fico<=624 THEN fico_range_25pt= "600-624";
IF 625<=fico<=649 THEN fico_range_25pt= "625-649";
IF 650<=fico<=674 THEN fico_range_25pt= "650-674";
IF 675<=fico<=699 THEN fico_range_25pt= "675-699";
IF 700<=fico<=724 THEN fico_range_25pt= "700-724";
IF 725<=fico<=749 THEN fico_range_25pt= "725-749";
IF 750<=fico<=774 THEN fico_range_25pt= "750-774";
IF 775<=fico<=799 THEN fico_range_25pt= "775-799";
IF 800<=fico<=824 THEN fico_range_25pt= "800-824";
IF 825<=fico<=849 THEN fico_range_25pt= "825-849";
IF 850<=fico<=874 THEN fico_range_25pt= "850-874";
IF 875<=fico<=899 THEN fico_range_25pt= "875-899";
IF 975<=fico<=999 THEN fico_range_25pt= "975-999";
IF fico="" THEN fico_range_25pt= "";
IF source_2 = "RETAIL" THEN CAMPAIGN_id = "&retail_id";
IF source_2 = "AUTO" THEN CAMPAIGN_id = "&auTO_id";
IF CAMP_TYPE="FB" THEN CAMPAIGN_id = "&fb_id";
IF POFFDATE > "&_1month" THEN RECENTPyout="Yes";
ELSE RECENTPyout="No";
IF month_split="&odd_even" | RECENTPyout="Yes";
custid=STRIP(_n_);
IF CAMP_TYPE="FB" THEN do;
IF lnamt >= 1500 & times30 = 0 THEN risk_segment = "A";
IF lnamt >= 1500 & FIRST6 > 0 THEN risk_segment = "A AND B";
IF lnamt >= 1500 & FIRST6 = . & times30 NE 0 THEN risk_segment = "A AND B";
IF lnamt >= 1500 & times30 NE 0 THEN risk_segment = "A AND B";
IF lnamt < 1500 THEN risk_segment="A AND B";
IF OWNBR="1019" THEN risk_segment="AL";
end;
RUN;
DATA fINalhh2;
SET fINalhh2;
rename brno=BRANCH FIRSTNAME=cfname1 middlename=cmname1 LASTNAME=clname1 ADR1=caddr1 ADR2=caddr2
CITY=cCITY STATE=cst ZIP=cZIP SSNO1_RT7=ssn cd60=n_60_dpd CONPROFILE1=ConPrOFile;
RUN;




PROC import 
	DATAfile="\\mktg-app01\E\Production\Master Files AND INstructions\FBXSCC_OFfers - 20180402.xlsx" 
		dbms=excel 
		out=OFfers 
		replace; 
RUN;

DATA OFfers;
	SET OFfers;
	risk_segment=STRIP(risk_segment);
RUN;

PROC SORT 
	DATA=fINalhh2; 
	BY cst risk_segment; 
RUN;

PROC SORT 
	DATA=OFfers; 
	BY cst risk_segment; 
RUN;

DATA fINalhh4;
	MERGE fINalhh2(IN=x) OFfers;
	BY cst risk_segment;
	IF x;
	format amt_given1 dollar10.2;
	rename apr=percent;
RUN;

*IF risk_segment="Test" THEN test_code="Rate_Test";
*ELSE test_code="Control";


PROC sql;
create table fINalhh5 as
select custid, BRANCH, cfname1,	cmname1, clname1, caddr1, caddr2, cCITY, cst, cZIP,	ssn, amt_given1, percent,	numpymnts, CAMP_TYPE, orig_amtid, fico, DOB, mla_status, risk_segment, n_60_dpd, conprOFile, bracctno, cIFno, campaign_id, mgc, month_split, MADE_UNMADE, fico_range_25pt, STATE1, test_code, POFFDATE, phoNE, cellphoNE
from fINalhh4;
quit;
RUN;


PROC export DATA=fINalhh5 outfile="&fINalexportHH"  dbms=tab;
 RUN;

 PROC export DATA=fINalhh5 outfile="&fINalexportED" dbms=csv;
 RUN;




DATA check;
SET fINalhh5;
IF amt_given1="";
RUN;

PROC freq DATA=fINalhh5;
tables Risk_Segment;
RUN;

PROC freq DATA=fINalhh5;
tables month_split;
RUN;





 
/*
DATA NOTest test;
SET fINalhh2;
IF cst = "AL" & risk_segment="A" THEN OUTPUT test;
ELSE OUTPUT NOTest;
RUN;
PROC surveyselect DATA=test out=test2 outall rate=.5 method=srs;
RUN;
DATA fINalhh3;
SET NOTest test2;
IF selected=1 THEN risk_segment="Test";
IF selected=0 THEN risk_segment="A";
risk_segment=STRIP(risk_segment);
RUN;
PROC freq DATA=fINalhh3;
tables Risk_Segment;
RUN;
 PROC freq DATA=fINalhh5;
tables test_code;
RUN;
*/